package tunnel

import (
	"bufio"
	"context"
	"crypto/subtle"
	"crypto/tls"
	"io"
	"log/slog"
	"net"
	"strings"
	"time"

	"github.com/hashicorp/yamux"

	"github.com/althq/netknownsthat/internal/auth"
)

// ListenerConfig configures the host-side reverse-tunnel listener — see Run.
type ListenerConfig struct {
	// ListenAddr is where this host accepts the hub's dial-in, e.g.
	// "0.0.0.0:8078" — written by the hub at install time as
	// NKT_HUB_TUNNEL_LISTEN_ADDR (see internal/hub/provision.go's renderEnv).
	ListenAddr string
	// Token is the shared per-host secret a connecting hub must present
	// before its connection is ever wrapped in yamux — see WriteToken/
	// readToken. Generated by the hub, written into this host's env
	// alongside ListenAddr.
	Token string
	// TLSCert is this host's own self-signed certificate for the listener
	// — generated and persisted once by the caller (cmd/nkt/main.go, via
	// internal/tlscert), not by this package: the hub does not validate it
	// (see this package's own doc comment on why), so there is nothing
	// here that needs to coordinate with the hub about it.
	TLSCert tls.Certificate
	// LocalAddr is where this host's own nkt API listens — every stream
	// the hub opens over the tunnel gets piped here. Almost always
	// 127.0.0.1:<NKT_ADDR's port>, the same loopback address the
	// SSH-tunneled path already reaches today.
	LocalAddr string
	Log       *slog.Logger
}

// tokenReadTimeout bounds how long an accepted connection has to present
// its token before this host gives up on it — without this, a connection
// that never sends anything (a port scanner, a client that stalls) would
// tie up a goroutine and a slot in the attempt limiter's bookkeeping
// forever instead of being reclaimed.
const tokenReadTimeout = 5 * time.Second

// Run accepts the hub's reverse-tunnel connections until ctx is cancelled.
// Meant to run as a long-lived background goroutine — see cmd/nkt/main.go's
// runServer, mirroring the same ctx-driven lifecycle every other background
// job there already uses. Returns only once the listener itself is closed
// (by ctx cancellation) or fails to bind in the first place.
func Run(ctx context.Context, cfg ListenerConfig) error {
	ln, err := tls.Listen("tcp", cfg.ListenAddr, &tls.Config{
		Certificates: []tls.Certificate{cfg.TLSCert},
	})
	if err != nil {
		return err
	}
	go func() {
		<-ctx.Done()
		_ = ln.Close()
	}()

	cfg.Log.Info("fallback channel: listening for hub connections", "addr", cfg.ListenAddr)

	attempts := auth.NewAttemptLimiter()
	for {
		conn, err := ln.Accept()
		if err != nil {
			if ctx.Err() != nil {
				return nil
			}
			cfg.Log.Warn("резервный канал: ошибка приёма соединения", "err", err)
			continue
		}
		go handleConn(ctx, cfg, conn, attempts)
	}
}

// handleConn checks one accepted connection's token and, if it matches,
// serves it until it closes — a wrong or missing token gets the connection
// closed immediately, with the attempt counted against whichever address
// presented it (see tokenReadTimeout on why a connection that never sends
// anything at all doesn't just hang here).
func handleConn(ctx context.Context, cfg ListenerConfig, conn net.Conn, attempts *auth.AttemptLimiter) {
	defer conn.Close()
	remote := conn.RemoteAddr().String()

	if !attempts.Allow(remote) {
		return
	}

	_ = conn.SetReadDeadline(time.Now().Add(tokenReadTimeout))
	reader := bufio.NewReader(conn)
	token, err := readToken(reader)
	_ = conn.SetReadDeadline(time.Time{})
	if err != nil {
		attempts.Fail(remote)
		return
	}
	if subtle.ConstantTimeCompare([]byte(token), []byte(cfg.Token)) != 1 {
		attempts.Fail(remote)
		cfg.Log.Warn("резервный канал: неверный токен", "remote", remote)
		return
	}
	attempts.Clear(remote)

	// reader may already have buffered bytes read past the token line
	// (yamux's own opening frames, if the hub sent them right away) — a
	// plain conn from here on would silently drop them. wrappedConn keeps
	// reading through the same bufio.Reader while writes/close still go
	// straight to the underlying connection.
	wrapped := wrappedConn{Reader: reader, Writer: conn, Closer: conn}
	session, err := yamux.Server(wrapped, Config())
	if err != nil {
		cfg.Log.Warn("резервный канал: настройка мультиплексирования", "remote", remote, "err", err)
		return
	}
	defer session.Close()

	cfg.Log.Info("резервный канал: хаб подключился", "remote", remote)
	go func() {
		<-ctx.Done()
		_ = session.Close()
	}()

	for {
		stream, err := session.Accept()
		if err != nil {
			cfg.Log.Info("резервный канал: хаб отключился", "remote", remote)
			return
		}
		go pipeStream(cfg, stream)
	}
}

// readToken reads the token line WriteToken sent — see its own doc comment.
func readToken(r *bufio.Reader) (string, error) {
	line, err := r.ReadString('\n')
	if err != nil {
		return "", err
	}
	return strings.TrimRight(line, "\n"), nil
}

// wrappedConn adapts a bufio.Reader (which may hold bytes already read off
// the wire past the token line) plus the original connection's Write/Close
// into the io.ReadWriteCloser yamux.Server needs.
type wrappedConn struct {
	io.Reader
	io.Writer
	io.Closer
}

// pipeStream connects one hub-opened virtual stream to this host's own
// local nkt listener — the same thing an SSH-forwarded channel does today
// for Proxy(), just carried over the tunnel instead.
func pipeStream(cfg ListenerConfig, stream net.Conn) {
	defer stream.Close()
	local, err := net.DialTimeout("tcp", cfg.LocalAddr, 5*time.Second)
	if err != nil {
		cfg.Log.Warn("резервный канал: не удалось подключиться к локальному nkt", "addr", cfg.LocalAddr, "err", err)
		return
	}
	defer local.Close()

	done := make(chan struct{}, 2)
	go func() {
		_, _ = io.Copy(local, stream)
		done <- struct{}{}
	}()
	go func() {
		_, _ = io.Copy(stream, local)
		done <- struct{}{}
	}()
	// Either direction finishing (the hub closed its side, or the local
	// nkt did) means this stream is done — both Close defers above then
	// unblock whichever io.Copy is still running.
	<-done
}
