// Package tunnel implements the reverse-tunnel fallback channel between a
// hub and a managed host, used when SSH becomes unreachable (a blocked or
// misconfigured inbound port 22 is the common real-world case — not
// necessarily sshd itself being down).
//
// The hub dials OUT to the host (see internal/hub's tunneldial.go) and
// multiplexes the connection with yamux, opening one virtual stream per
// proxied dashboard API request (or one long-lived one for the terminal's
// own WebSocket) — each piped by the host into its own local nkt listener
// (see Run in this package, the host side). Deliberately the same direction
// SSH itself already uses: the hub reaching out to a known host address,
// not the host reaching out to a hub address that may not even have one
// (NAT, no public IP — a hub run on a home/office LAN is a normal setup,
// not an edge case).
//
// Authentication is a shared per-host token, generated by the hub and
// pushed to the host's env at install time over the already-trusted SSH
// session — presented by the hub as the first thing after the TLS
// handshake, checked by the host before it ever wraps the connection in
// yamux. The host's own TLS certificate is not pinned or otherwise
// verified by the hub (InsecureSkipVerify) — the same trust-on-first-use
// trade-off internal/hub/ssh.go already makes for SSH host keys in this
// codebase: the token is what actually authenticates the hub to the host,
// TLS here is for confidentiality in transit, not identity.
package tunnel

import (
	"io"

	"github.com/hashicorp/yamux"
)

// WriteToken sends the shared per-host token as the first thing after a
// freshly dialed connection completes — read by the host's listener before
// it ever wraps the connection in yamux (see readToken). A trailing
// newline terminates it; the token's own alphabet (base64 URL, see
// internal/hub's generatePassword) never contains one, so a bare
// line-read on the other side is unambiguous.
func WriteToken(w io.Writer, token string) error {
	_, err := io.WriteString(w, token+"\n")
	return err
}

// Config returns the yamux configuration both sides use — yamux's own
// defaults, except its internal transport-level logging (connection
// resets, closed-session reads — expected and already surfaced through
// this package's own error returns/slog calls at the point they matter) is
// discarded instead of going straight to os.Stderr.
func Config() *yamux.Config {
	cfg := yamux.DefaultConfig()
	cfg.LogOutput = io.Discard
	return cfg
}
