package msgs

// enCLICatalog — строки командной строки nkt (cmd/nkt, ключи cli.*): справка,
// флаги, отчёт scan, passwd/users, hub delete/import. Язык выбирается по
// локали терминала (cmd/nkt/cli_lang.go).
func init() {
	for k, v := range enCLICatalog {
		enCatalog[k] = v
	}
}

// #nosec G101 -- тексты сообщений командной строки (ключи вроде cli.passwd.prompt), а не учётные данные.
var enCLICatalog = map[string]string{
	"cli.flag.verbose":           "verbose log",
	"cli.flag.scan":              "one-off check and exit",
	"cli.flag.version":           "show the version and exit",
	"cli.flag.random":            "generate a password instead of typing one",
	"cli.flag.role":              "role of the account being created: admin or viewer",
	"cli.flag.yes":               "in hub delete: do not ask for confirmation",
	"cli.flag.export":            "in hub delete: save a host export with the key here before deleting",
	"cli.flag.noExport":          "in hub delete: do not offer or make an export before deleting",
	"cli.flag.file":              "in hub import: path to the export file (plain or password-encrypted)",
	"cli.usage":                  "NetKnownsThat %s — network resource map and host configuration checks.\n\nUsage:\n  nkt [serve]         run the web dashboard and background collection (default)\n  nkt tui             terminal interface: the same without a browser\n  nkt scan            one-off check, report to stdout, exit code 2 on critical findings\n  nkt hub             control center: installs and proxies nkt on other hosts over SSH\n  nkt hub delete      irreversibly erase the hub's data and keys (service and binary stay)\n  nkt hub import -file <file>   restore hosts from an export (plain or password-protected)\n  nkt users           list web interface accounts\n  nkt passwd [login]  change a password (admin by default), asked without echo\n  nkt version         show the version\n\nFlags:\n  -v                  verbose log\n  -random             in passwd: generate a password and print it once\n  -role admin|viewer  in passwd: create the account with this role if it does not exist\n  -yes                in hub delete: do not ask for confirmation\n  -export <file>      in hub delete: save a host export with the key here before deleting\n  -no-export          in hub delete: do not offer or make an export before deleting\n  -file <file>        in hub import: path to the export file\n\nExamples:\n  sudo nkt passwd                     change the administrator password\n  sudo nkt passwd ops -role viewer    create a read-only account\n  sudo nkt passwd -random             issue a new random admin password\n  sudo nkt hub delete                 delete the hub: asks about the export and confirmation\n  sudo nkt hub delete -export a.json  delete the hub, saving an export to a.json first\n  sudo nkt hub import -file a.json    restore hosts from a previously saved export\n\nConfiguration is via NKT_* environment variables, see deploy/nkt.env.example.\n",
	"cli.unknownCommand":         "unknown command %q",
	"cli.scan.host":              "Host:       %s (%s, mode %s)\n",
	"cli.scan.took":              "Scan:       %s in %d ms\n",
	"cli.scan.found":             "Found:      %d listeners in configs, %d pools, %d containers, %d firewall rules\n\n",
	"cli.scan.sourceError":       "ERROR: %s",
	"cli.scan.sourceUnavailable": "unavailable",
	"cli.scan.problems":          "\nProblems: critical=%d high=%d medium=%d low=%d info=%d\n",
	"cli.scan.finding":           "\n[%s] %s\n    object: %s\n    %s\n",
	"cli.dataDir":                "data directory %s: %v\nthe hub runs as uid %d; give it the data directory, for example:\n  docker run --rm -v <volume>:/data alpine chown -R 1000:1000 /data",
	"cli.dataDirNotWritable":     "data directory %s is not writable: %v\nthe hub runs as uid %d; give it the data directory, for example:\n  docker run --rm -v <volume>:/data alpine chown -R 1000:1000 /data",
	"cli.users.none":             "No accounts. Start nkt — the administrator is created on first start.",
	"cli.users.colLogin":         "LOGIN",
	"cli.users.colRole":          "ROLE",
	"cli.users.colState":         "STATE",
	"cli.users.colCreated":       "CREATED",
	"cli.users.colLast":          "LAST SIGN-IN",
	"cli.users.active":           "active",
	"cli.users.disabled":         "disabled",
	"cli.users.never":            "never",
	"cli.passwd.noAccount":       "there is no account %q. Existing ones: nkt users. To create a new one, give a role: nkt passwd %s -role admin",
	"cli.passwd.badRole":         "the role must be admin or viewer, got %q",
	"cli.passwd.tooShort":        "the password must be at least %d characters",
	"cli.passwd.createFailed":    "creating the account: %v",
	"cli.passwd.created":         "Created account %s with role %s.\n",
	"cli.passwd.setFailed":       "changing the password: %v",
	"cli.passwd.roleFailed":      "changing the role: %v",
	"cli.passwd.roleChanged":     "Role of %s changed to %s.\n",
	"cli.passwd.changed":         "Password of %s changed, all its sessions ended.\n",
	"cli.passwd.generated":       "\n  login:    %s\n  password: %s\n\n  Save the password: it is not shown anywhere again.\n",
	"cli.passwd.prompt":          "New password: ",
	"cli.passwordRepeat":         "Repeat the password: ",
	"cli.passwordMismatch":       "the passwords do not match",
	"cli.needsHubMode":           "%s requires NKT_MODE=hub, currently %q",
	"cli.hubKey":                 "the hub's secret encryption key: %v",
	"cli.delete.canceled":        "Cancelled, nothing deleted.",
	"cli.delete.wiping":          "Wiping %s…\n",
	"cli.delete.failed":          "deleting the hub's data: %v",
	"cli.delete.done":            "Done: the encryption key, the database (including SSH and admin secrets of all connected hosts), config history and the TLS key in %s were overwritten and deleted; the binary cache and Go toolchain were simply deleted (they hold no secrets, only public code).\nThe hosts themselves and the nkt installed on them are not touched — only what the hub knew about them.\nThe hub's binary and systemd unit stay in place: `sudo systemctl start netknownsthat-hub` starts a completely new hub — a new key, a new administrator account.\n",
	"cli.delete.yesNeedsExport":  "with -yes, give -export <file> or -no-export explicitly — without a terminal there is no way to ask whether a backup is needed before an irreversible deletion",
	"cli.delete.noTerminal":      "standard input is not a terminal — give -export <file> or -no-export explicitly",
	"cli.delete.askExport":       "Save a host export with the key before deleting, for restoring? [Y/n]: ",
	"cli.delete.askPath":         "Where to save the export file: ",
	"cli.delete.noPath":          "no export path given",
	"cli.export.warn":            "The export file is plain JSON with the hub's encryption key and the SSH/admin secrets\nof all hosts inside: whoever gets the file gets them. It is STRONGLY\nrecommended to encrypt it with a password right now rather than keep it as is.",
	"cli.export.askPassword":     "Password to encrypt the file (empty — no encryption, not recommended): ",
	"cli.export.prepare":         "preparing the export: %v",
	"cli.export.marshal":         "serializing the export: %v",
	"cli.export.encrypt":         "encrypting the export with a password: %v",
	"cli.export.write":           "writing %s: %v",
	"cli.export.savedEncrypted":  "The export with the key is encrypted with a password and saved to %s (%d hosts). Restore it with `nkt hub import -file %s`. Without the password the file is useless, but keep the password apart from the file (not next to it, not in the same conversation) — otherwise encryption gives nothing.\n",
	"cli.export.savedPlain":      "\n!!! The export with the key is saved WITHOUT ENCRYPTION to %s (%d hosts). !!!\nThis is a plain file: the hub's encryption key and the SSH/admin secrets of all hosts can be read from it directly, without a password. Keep and pass it around as carefully as a password file, and delete it as soon as it is no longer needed.\n\n",
	"cli.delete.confirm":         "\nWARNING: this irreversibly erases (overwriting the content, not just rm) the encryption key, the hub database — including SSH and admin secrets of ALL connected hosts — the binary cache and config history in %s.\nThe managed hosts themselves and nkt on them are not touched — only what this hub knew about them.\n\nType “%s” to continue: ",
	"cli.delete.word":            "delete",
	"cli.delete.shred":           "overwriting %s: %v",
	"cli.delete.remove":          "deleting %s: %v",
	"cli.import.noFile":          "give the export file: nkt hub import -file <file>",
	"cli.import.read":            "reading %s: %v",
	"cli.import.section":         "%s: added %d, replaced %d, skipped (already there) %d\n",
	"cli.import.error":           "  error: %s\n",
	"cli.import.errors":          "import errors: %d",
	"cli.import.noTerminal":      "the file is password-encrypted and standard input is not a terminal — set NKT_HUB_EXPORT_PASSWORD",
	"cli.import.askPassword":     "The file is password-encrypted. Password: ",
}
