package msgs

// fail2ban section messages (host and hub) — a separate file, like the TUI.
func init() {
	for k, v := range enFail2banCatalog {
		enCatalog[k] = v
	}
}

var enFail2banCatalog = map[string]string{
	"f2b.alreadyInstalled":    "fail2ban is already installed",
	"f2b.notInstalled":        "fail2ban is not installed",
	"f2b.badBanTime":          "Ban time must be between a minute and 10 years",
	"f2b.badIP":               "Not an IPv4/IPv6 address: %q",
	"f2b.badJail":             "No such jail: %q",
	"f2b.badLogPath":          "The log to test against must be a file under /var/log or systemd-journal, not %q",
	"f2b.badTemplateName":     "A template name is lowercase latin letters, digits, “-” and “_”, up to 41 characters: %q",
	"f2b.banHub":              "%s is the hub's external address: banning it would cut the hub off from the host",
	"f2b.banLoopback":         "%s is a local address, banning it makes no sense",
	"f2b.banSelf":             "%s is your own address: banning it would cut you off from the host",
	"f2b.commandFailed":       "fail2ban-client %s: exit code %d: %s",
	"f2b.configsUnavailable":  "The configuration editor is unavailable",
	"f2b.emptyFilter":         "Empty filter: at least one failregex line is needed",
	"f2b.noIPs":               "No addresses given",
	"f2b.tooManyIPs":          "Too many addresses at once: %d (256 at most)",
	"f2b.noteHub":             "Lock-out protection: hub address %s in ignoreip",
	"f2b.noteManual":          "nkt manual bans jail",
	"f2b.noteSetup":           "nkt fail2ban setup",
	"f2b.noteTemplate":        "Template “%s”",
	"f2b.templateDeletedNote": "Template deleted",
	"f2b.templateNoJail":      "The jail text has no [jail-name] section",
	"f2b.templateNotFound":    "No template %q",
	"f2b.templateTooLarge":    "The template is too large (jail and filter up to 64 KB, description up to 500 characters)",

	"finding.f2bMissing.title":            "SSH is exposed and fail2ban is not installed",
	"finding.f2bMissing.detail":           "SSH password guessing is not limited in any way: every address can try as much as it wants.",
	"finding.f2bMissing.suggestion":       "“fail2ban” → “Install”: nkt installs the package, enables the sshd jail and adds the hub's address to the exceptions.",
	"finding.f2bStopped.title":            "fail2ban is installed but not running",
	"finding.f2bStopped.detail":           "The fail2ban server does not respond, so nothing gets banned. %s",
	"finding.f2bStopped.suggestion":       "“fail2ban” → “Set up”, or “Services” → fail2ban → log: most often a jail points at a log that does not exist.",
	"finding.f2bNoSSHJail.title":          "fail2ban does not protect SSH",
	"finding.f2bNoSSHJail.detail":         "SSH is exposed, and there is no sshd jail among the running ones.",
	"finding.f2bNoSSHJail.suggestion":     "“fail2ban” → “Templates” → sshd.",
	"finding.f2bDeadJail.title":           "Jail %s sees nothing",
	"finding.f2bDeadJail.detail":          "The jail's log files are not on disk: %s. The jail runs but has nothing to ban on.",
	"finding.f2bDeadJail.suggestion":      "Fix the jail's logpath or switch it to journald (backend = systemd).",
	"finding.f2bHubNotIgnored.title":      "The hub (%s) can ban itself",
	"finding.f2bHubNotIgnored.detail":     "The hub's address is not in the ignoreip of jails: %s. A few failed hub connections and it loses the host.",
	"finding.f2bHubNotIgnored.suggestion": "“fail2ban” → “Set up”: nkt adds the hub's address to [DEFAULT] ignoreip. If a jail has its own ignoreip, add the address there too.",

	"hub.newBans":            "fail2ban banned new addresses (%d): %s",
	"hub.f2bNoSSHConnection": "the host did not report SSH_CONNECTION",
	"hub.f2bBadAction":       "Unknown action: %q (ban or unban expected)",
	"hub.f2bNoHosts":         "No hosts with fail2ban",
	"hub.f2bJobBan":          "Ban %s on hosts (%d)",
	"hub.f2bJobUnban":        "Unban %s on hosts (%d)",
	"hub.f2bHostGone":        "Host #%d is gone, skipped",
	"hub.f2bStep":            "Host %s",
	"hub.f2bHostDone":        "%s: done",
	"hub.f2bHostOld":         "%s: an old nkt version without fail2ban, skipped; update nkt",
	"hub.f2bHostNoFail2ban":  "%s: fail2ban is not installed, skipped",
	"hub.f2bHostFailed":      "%s: error: %s",
	"hub.f2bFailedCount":     "Failed on %d of %d hosts",
	"hub.f2bNoLocal":         "The hub machine's built-in API is unavailable",
	"hub.aiIPPrivate":        "Address type: private/local, an internal network address rather than the internet.",
	"hub.aiIPPublic":         "Address type: public (internet).",
	"hub.aiIPReverse":        "Reverse DNS: %s",
	"hub.aiIPNoReverse":      "Reverse DNS: no record.",
	"hub.aiIPBannedOn":       "Currently banned in %d entries (hosts with fail2ban: %d): %s",
	"hub.aiIPNotBanned":      "Not banned on any host right now (hosts with fail2ban: %d).",
	"hub.aiIPLog":            "fail2ban log of host %s over 7 days: %d lines with the address; events: %s. Latest:",
	"hub.aiIPNoLog":          "The address does not appear in the hosts' fail2ban logs over 7 days (or the logs are unavailable).",
	"hub.aiIPEvents":         "Mentions in hub alerts: %d, the latest at %s.",
}
