package msgs

// Выкладка compose-стеков и сайты — отдельным файлом.
func init() {
	for k, v := range enSitesCatalog {
		enCatalog[k] = v
	}
}

var enSitesCatalog = map[string]string{
	"compose.badPath":          "Invalid stack file path: %q",
	"compose.badProject":       "A stack name is lowercase latin letters, digits, “-” and “_”: %q",
	"compose.commandFailed":    "docker compose %s: exit code %d",
	"compose.configRejected":   "compose rejected the stack description: %s",
	"compose.done":             "Stack %s is up",
	"compose.jobTitle":         "Deploy stack %s",
	"compose.noEngine":         "The host has neither docker nor podman",
	"compose.noFile":           "No stack compose file: %q",
	"compose.stepPull":         "Images of stack %s",
	"compose.stepStatus":       "State of stack %s",
	"compose.stepUp":           "Bringing stack %s up",
	"compose.tooLarge":         "The stack files are too large (4 MB and 200 files at most)",
	"compose.waitTimeout":      "The containers of stack %s did not come up within %d s",
	"site.badDomain":           "Invalid site name: %q",
	"site.badOverride":         "The nkt publishing file is damaged: %s",
	"site.badProxy":            "Unknown proxy: %q (nginx, haproxy, caddy)",
	"site.badTarget":           "The site target is a stack, a service and a container port",
	"site.badUpstream":         "The target address is an IP or localhost with a port: %q",
	"site.caddyOwnCert":        "Caddy obtains and renews the certificate itself; certbot is not needed",
	"site.certExisting":        "Certificate %s is valid for %d more days and is used",
	"site.certNotFound":        "No certificate for %s found after issuance",
	"site.done":                "Site %s is set up → %s",
	"site.firewallClosedSkip":  "%s: ports 80/443 look closed and opening them was not requested; skipping",
	"site.firewallOff":         "The host firewall is off, nothing to open",
	"site.firewallOpen":        "%s: ports 80/443 are already open",
	"site.firewallOpened":      "%s: ports 80 and 443 opened",
	"site.haproxyForeignBind":  "HAProxy already listens on port %s in its own frontend; two frontends on one port are impossible, so add a backend to it by hand or free the port",
	"site.jobTitle":            "Site %s",
	"site.nginxNoConfD":        "%s does not include conf.d/*.conf, so nkt has nowhere to put the site",
	"site.noCertbot":           "The host has no certbot; install it in “Packages”",
	"site.noDomain":            "No site name given",
	"site.noFreePort":          "No free local port in 18000–18999",
	"site.notFound":            "The host has no site %s",
	"site.noteOverride":        "Service published for site %s",
	"site.noteProxy":           "Site %s",
	"site.noteRemoved":         "Site %s removed",
	"site.portPublic":          "Service %s is already published on port %d of all addresses, so it is reachable bypassing the proxy; better bind it to 127.0.0.1 in the compose file",
	"site.proxyMissing":        "%s is not installed",
	"site.proxyRejected":       "The %s configuration failed its check and was rolled back: %s",
	"site.proxyStarted":        "%s started",
	"site.proxyWritten":        "Written: %s",
	"site.published":           "Service %s published on 127.0.0.1:%d (container port %d)",
	"site.serviceMissing":      "Stack %[2]s has no service %[1]s",
	"site.stackMissing":        "No stack %s in /srv/compose",
	"site.stepCert":            "Certificate: %s",
	"site.stepCheck":           "Check: %s",
	"site.stepFirewall":        "Firewall",
	"site.stepProxy":           "Proxy: %s",
	"site.stepTarget":          "Site target",
	"site.tooManyDomains":      "Too many names: %d (20 at most)",
	"site.upstream":            "The proxy will point at %s",
	"compose.buildOnly":        "service %s is built from source (build:) — specify a ready image (image:): deployments take ready images only; building is the job of CI",
	"deploy.composeBinary":     "%s is a binary file: stack files travel to the host as text; binaries belong in the image",
	"deploy.composeFiles":      "Stack files: %d, stack %s, hosts: %d",
	"deploy.composeHostDone":   "%s: the stack is up",
	"deploy.composeHostFailed": "%s: %s; the remaining hosts were not touched",
	"deploy.composeNote":       "Pipeline %s, commit %s",
	"deploy.composeOutside":    "%s is outside the compose file's directory %s, so compose's relative references to it will not work",
	"deploy.hostUnknown":       "The hub has no host %q",
	"deploy.noHosts":           "No running host to deploy to",
	"deploy.siteFailed":        "Site %s did not answer over HTTPS: %s",
	"deploy.siteOK":            "Site %s answers: HTTP %d, certificate valid for %d more days",
	"deploy.stepCompose":       "Stack on %s",
	"hub.siteDNSMismatch":      "%s points at %s while the host has %s; the certificate issuance will most likely fail",
	"hub.siteDNSOK":            "%s → %s, that is the host",
	"hub.siteExists":           "Site %s already exists",
	"hub.siteHTTPSFailed":      "%s did not answer from outside: %s (DNS may not have propagated yet, the service may still be starting)",
	"hub.siteHTTPSOK":          "https://%s answers: HTTP %d, certificate valid for %d more days",
	"hub.siteInstallingProxy":  "%s is not installed; installing",
	"hub.siteJobTitle":         "Site %s",
	"hub.siteLAN":              "The name points into a private network: the hub sees the ports from inside, the internet may see them differently",
	"hub.sitePort":             "Port %s from outside: %s",
	"hub.sitePort80Blocked":    "Port 80 does not answer even with a refusal; the provider's firewall or NAT seems to block it, so Let's Encrypt will not reach the host",
	"hub.siteStepDNS":          "DNS: %s",
	"hub.siteStepHTTPS":        "Checking https://%s",
	"hub.siteStepHost":         "Setting up on %s",
	"hub.siteStepPorts":        "Ports 80 and 443 from outside",
	"hub.siteStepProxy":        "Proxy: %s",
}
