package msgs

// Выкладка compose-стеков и сайты — отдельным файлом.
func init() {
	for k, v := range enSitesCatalog {
		enCatalog[k] = v
	}
}

var enSitesCatalog = map[string]string{
	"compose.badPath":               "Invalid stack file path: %q",
	"compose.badProject":            "A stack name is lowercase latin letters, digits, “-” and “_”: %q",
	"compose.commandFailed":         "docker compose %s: exit code %d",
	"compose.configRejected":        "compose rejected the stack description: %s",
	"compose.done":                  "Stack %s is up",
	"compose.jobTitle":              "Deploy stack %s",
	"compose.noEngine":              "The host has neither docker nor podman",
	"compose.noFile":                "No stack compose file: %q",
	"compose.stepPull":              "Images of stack %s",
	"compose.stepStatus":            "State of stack %s",
	"compose.stepUp":                "Bringing stack %s up",
	"compose.tooLarge":              "The stack files are too large (4 MB and 200 files at most)",
	"compose.waitTimeout":           "The containers of stack %s did not come up within %d s",
	"site.badDomain":                "Invalid site name: %q",
	"site.badOverride":              "The nkt publishing file is damaged: %s",
	"site.badProxy":                 "Unknown proxy: %q (nginx, haproxy, caddy)",
	"site.badTarget":                "The site target is a stack, a service and a container port",
	"site.badUpstream":              "The target address is an IP or localhost with a port: %q",
	"site.caddyOwnCert":             "Caddy obtains and renews the certificate itself; certbot is not needed",
	"site.certExisting":             "Certificate %s is valid for %d more days and is used",
	"site.certNotFound":             "No certificate for %s found after issuance",
	"site.done":                     "Site %s is set up → %s",
	"site.firewallClosedSkip":       "%s: ports 80/443 look closed and opening them was not requested; skipping",
	"site.firewallOff":              "The host firewall is off, nothing to open",
	"site.firewallOpen":             "%s: ports 80/443 are already open",
	"site.firewallOpened":           "%s: ports 80 and 443 opened",
	"site.haproxyForeignBind":       "HAProxy already listens on port %s in its own frontend; two frontends on one port are impossible, so add a backend to it by hand or free the port",
	"site.jobTitle":                 "Site %s",
	"site.nginxNoConfD":             "%s does not include conf.d/*.conf, so nkt has nowhere to put the site",
	"site.noCertbot":                "The host has no certbot; install it in “Packages”",
	"site.noDomain":                 "No site name given",
	"site.noFreePort":               "No free local port in 18000–18999",
	"site.notFound":                 "The host has no site %s",
	"site.noteOverride":             "Service published for site %s",
	"site.noteProxy":                "Site %s",
	"site.noteRemoved":              "Site %s removed",
	"site.portPublic":               "Service %s is already published on port %d of all addresses, so it is reachable bypassing the proxy; better bind it to 127.0.0.1 in the compose file",
	"site.proxyMissing":             "%s is not installed",
	"site.proxyRejected":            "The %s configuration failed its check and was rolled back: %s",
	"site.proxyStarted":             "%s started",
	"site.proxyWritten":             "Written: %s",
	"site.published":                "Service %s published on 127.0.0.1:%d (container port %d)",
	"site.serviceMissing":           "Stack %[2]s has no service %[1]s",
	"site.stackMissing":             "No stack %s in /srv/compose",
	"site.stepCert":                 "Certificate: %s",
	"site.stepCheck":                "Check: %s",
	"site.stepFirewall":             "Firewall",
	"site.stepProxy":                "Proxy: %s",
	"site.stepTarget":               "Site target",
	"site.tooManyDomains":           "Too many names: %d (20 at most)",
	"site.upstream":                 "The proxy will point at %s",
	"compose.buildOnly":             "service %s is built from source (build:) — specify a ready image: image: in the compose file or compose.images in the pipeline description (service: image); building is the job of CI",
	"deploy.composeBinary":          "%s is a binary file: stack files travel to the host as text; binaries belong in the image",
	"deploy.composeFiles":           "Stack files: %d, stack %s, hosts: %d",
	"deploy.composeHostDone":        "%s: the stack is up",
	"deploy.composeHostFailed":      "%s: %s; the remaining hosts were not touched",
	"deploy.composeNote":            "Pipeline %s, commit %s",
	"deploy.composeOutside":         "%s is outside the compose file's directory %s, so compose's relative references to it will not work",
	"deploy.hostUnknown":            "The hub has no host %q",
	"deploy.noHosts":                "No running host to deploy to",
	"deploy.siteFailed":             "Site %s did not answer over HTTPS: %s",
	"deploy.siteOK":                 "Site %s answers: HTTP %d, certificate valid for %d more days",
	"deploy.stepCompose":            "Stack on %s",
	"hub.siteDNSMismatch":           "%s points at %s while the host has %s; the certificate issuance will most likely fail",
	"hub.siteDNSOK":                 "%s → %s, that is the host",
	"hub.siteExists":                "Site %s already exists",
	"hub.siteHTTPSFailed":           "%s did not answer from outside: %s (DNS may not have propagated yet, the service may still be starting)",
	"hub.siteHTTPSOK":               "https://%s answers: HTTP %d, certificate valid for %d more days",
	"hub.siteInstallingProxy":       "%s is not installed; installing",
	"hub.siteJobTitle":              "Site %s",
	"hub.siteLAN":                   "The name points into a private network: the hub sees the ports from inside, the internet may see them differently",
	"hub.sitePort":                  "Port %s from outside: %s",
	"hub.sitePort80Blocked":         "Port 80 does not answer even with a refusal; the provider's firewall or NAT seems to block it, so Let's Encrypt will not reach the host",
	"hub.siteStepDNS":               "DNS: %s",
	"hub.siteStepHTTPS":             "Checking https://%s",
	"hub.siteStepHost":              "Setting up on %s",
	"hub.siteStepPorts":             "Ports 80 and 443 from outside",
	"hub.siteStepProxy":             "Proxy: %s",
	"compose.checkNoSkopeo":         "podman without skopeo: cannot check the image in the registry",
	"compose.dockerInstalled":       "Docker with compose is already installed: %s",
	"deploy.composeEngines":         "The stack cannot be started; no host was touched: %s",
	"deploy.hostNoEngine":           "%s: neither docker nor podman",
	"deploy.hostNoCompose":          "%s: %s without a working compose (%s)",
	"deploy.dryOnlyCompose":         "A dry run is for action: compose pipelines",
	"deploy.dryTitle":               "Dry run of %s",
	"deploy.dryNewPipeline":         "a new pipeline",
	"deploy.stepDryHosts":           "Checking on hosts: %d",
	"deploy.stepDryResult":          "Result",
	"deploy.dryFiles":               "Stack files: %d, stack %s, hosts: %d, tag %s; nothing changes on the hosts",
	"deploy.dryOldHost":             "? %s: an old nkt version without dry run support; skipped",
	"deploy.dryHostError":           "✗ %s: %s",
	"deploy.dryNoEngine":            "✗ %s: neither docker nor podman; use \"Install Docker\" for the host",
	"deploy.dryNoCompose":           "✗ %s: %s, but compose does not work: %s",
	"deploy.dryEngine":              "%s: %s; compose %s",
	"deploy.drySimulated":           "%s: %s (fixtures: the commands did not really run)",
	"deploy.dryStackExists":         "  stack %s exists: new files %d, changed %d, unchanged %d %s",
	"deploy.dryStackNew":            "  stack %s will be created: %d files",
	"deploy.dryEnv.new":             "  .env: will be created",
	"deploy.dryEnv.changed":         "  .env: will change",
	"deploy.dryEnv.same":            "  .env: unchanged",
	"deploy.dryEnv.keep":            "  .env: the current one stays (not set in the pipeline)",
	"deploy.dryConfigBad":           "✗ compose rejected the stack: %s",
	"deploy.dryConfigOK":            "  compose config: accepted; services: %s",
	"deploy.dryImageRegistry":       "  image %s: in the registry",
	"deploy.dryImageLocal":          "  image %s: pulled on the host",
	"deploy.dryImageLocalOnly":      "  image %s: pulled on the host but not visible in the registry (pull will fail): %s",
	"deploy.dryImageMissing":        "✗ image %s: not in the registry: %s",
	"deploy.dryImageUnknown":        "? image %s: could not check: %s",
	"deploy.dryFailed":              "Dry run: %d problems; the deployment would fail",
	"deploy.dryOK":                  "Dry run: the deployment would succeed on all hosts (%d); nothing changed",
	"deploy.siteOneHost":            "compose.site as a block is a site on one host: list exactly one host in hosts (no group)",
	"deploy.siteSetup":              "Site %s: proxy %s on %s",
	"deploy.siteSetupFailed":        "? Site %s is not set up (the stack is deployed): %s",
	"deploy.siteOldHostLeft":        "? Site %s: could not remove the proxy config on the previous host: %s",
	"deploy.drySiteWarn":            "? site: %s",
	"deploy.drySiteNoService":       "? site: service %s is not in stack %s (it has: %s)",
	"deploy.drySiteProxy":           "  site: proxy %s",
	"deploy.drySiteProxyInstall":    "  site: proxy %s will be installed",
	"deploy.drySiteSame":            "  site %s is set up and unchanged; only an HTTPS check",
	"deploy.drySiteWill":            "  site %s will be set up: service %s, port %d",
	"deploy.drySiteDNS":             "? %s → %s, but the host is %s: no certificate until DNS points at the host",
	"deploy.drySiteNoDNS":           "? %s does not resolve in DNS: no certificate until an A record points at the host",
	"deploy.failedRemembered":       "Polling and the registry will not retry %s: the next deployment comes with a new commit or tag, or the button",
	"deploy.envEditedOverwritten":   "? %s: .env on the host was edited by hand; overwritten with the .env from \"Access\"",
	"deploy.dryEnvEdited":           "? .env on the host was edited by hand; the deployment will overwrite it with the .env from \"Access\"",
	"deploy.envVersionInitial":      "set before the history",
	"deploy.envVersionEdited":       "edited in \"Access\"",
	"deploy.envVersionCleared":      "removed in \"Access\"",
	"deploy.envVersionRestored":     "restored version #%d",
	"deploy.envVersionRollback":     "rollback to deployment #%d",
	"deploy.envVersionMissing":      "No .env version #%d",
	"compose.removeTitle":           "Removing stack %s",
	"compose.stepDown":              "Stopping and removing the containers of stack %s",
	"compose.stepDir":               "Stack directory %s",
	"compose.removeNoStack":         "No stack in %s; nothing to remove",
	"compose.removeDirSkipped":      "Fixtures: directory %s is left alone",
	"compose.removeDirFailed":       "Could not remove stack directory %s: %s",
	"compose.removeDirDeleted":      "Directory %s deleted together with its data",
	"compose.removeDirMoved":        "Directory %s moved to %s (data kept)",
	"compose.removed":               "Stack %s removed",
	"site.badLineage":               "Invalid certificate name: %s",
	"deploy.removeOnlyCompose":      "Removing from hosts is for action: compose pipelines; others are deleted from the hub only",
	"deploy.useRemove":              "A compose pipeline is deleted by a job that removes the stack from the hosts (the \"Delete\" button)",
	"deploy.removeTitle":            "Deleting pipeline %s",
	"deploy.removeStepSite":         "The pipeline's site",
	"deploy.removeStepHosts":        "Stack on hosts: %d",
	"deploy.removeStepHub":          "The hub record",
	"deploy.removeHostGone":         "? host %s is no longer on the hub; skipped",
	"deploy.removeHost":             "%s: removing stack %s",
	"deploy.removeHostFailed":       "%s: %s; the pipeline stays, use \"Retry\"",
	"deploy.removed":                "Pipeline %s removed from the hosts and the hub",
	"deploy.removeSite":             "Site %s: removing from the host",
	"deploy.removeSiteHostGone":     "? site %s: the host is no longer on the hub; only the record is removed",
	"deploy.removeSiteAlready":      "Site %s is already gone from the host",
	"deploy.removeSiteUnpublished":  "  the 127.0.0.1 publication of service %s is removed",
	"deploy.removeSiteStep":         "Site %s: %s",
	"deploy.removeSiteCert":         "  certificate %s deleted",
	"deploy.removeSiteCertShared":   "  another site needs the certificate; kept",
	"deploy.removeSiteFromPipeline": "? the site is described in a pipeline: the next deployment brings it back unless the site: block is removed",
	"hub.siteRemoveTitle":           "Removing site %s",
	"hub.siteRemoveStep":            "Removing %s from the host",
	"hub.siteRemoved":               "Site %s removed",
	"deploy.composeYAML":            "cannot parse the compose file: %s",
	"deploy.imageServiceMissing":    "compose.images / compose.ports: service %s is not in the compose file",
	"deploy.portBound":              "  port %s (%s) → %s",
	"deploy.portKept":               "  port %s (%s): the file sets an address; kept (bind_force: true replaces it)",
	"deploy.portSkipped":            "? port %s (%s): the entry uses a variable; no address set, give it in compose.ports",
	"ui.docsURLBad":                 "Docs address %s: needs http:// or https://, no login or parameters, ending with \"/\"",
	"site.portNotExposed":           "Port %d: service %s (image %s) does not declare it; it declares %s. Fix site.port (the port inside the container); no certificate was issued",
	"site.portUnverified":           "Image %s declares no ports; the site port cannot be checked",
	"site.portOK":                   "Container port %d is declared (%s)",
	"deploy.drySitePortBad":         "✗ site: port %d, but service %s (image %s) declares %s; the proxy would get 502, fix site.port",
	"deploy.drySitePortUnknown":     "? site: image %s declares no ports (or is not pulled yet); the port cannot be checked",
	"deploy.drySitePortOK":          "  site: port %d is declared by service %s",
	"hub.site502Hint":               "? 502: the proxy could not reach service %s; check that the container listens on port %d (site.port is the port inside the container)",
	"deploy.hostOld":                "? %s: an old nkt version does not know the fields %s; the request was repeated without them: the site port is not checked and hand edits of .env are not tracked. Update nkt on the host (\"Hosts\" → \"Update\")",
	"deploy.sitePortMissing":        "compose.site.port is not set; give the port inside the container that the image listens on (e.g. port: 80)",
	"deploy.drySitePortBadOne":      "✗ site: port %d, but image %s listens on %d; set port: %d",
	"deploy.sitePortsMismatch":      "? site: compose.ports publishes container port %[2]s of service %[1]s, but site.port is %[3]d; the site needs site.port (nkt publishes it for the site itself)",
}
