package msgs

// enTUICatalog is enTUICatalog's ru_tui.go counterpart — see that file's
// doc comment for why internal/tui gets its own file instead of living in
// en.go alongside the HTTP API's strings.
func init() {
	for k, v := range enTUICatalog {
		enCatalog[k] = v
	}
}

var enTUICatalog = map[string]string{
	"tui.loadingHostState":  "Loading host state…",
	"tui.globalHints":       "F5 refresh · r rescan · ? help · q quit",
	"tui.noProblemsFound":   "no problems found",
	"tui.needsAttention":    "needs attention: %d",
	"tui.notesCount":        "notes: %d",
	"tui.modeLabel":         "mode",
	"tui.scanLabel":         "scan",
	"tui.working":           "working…",
	"tui.readOnly":          "read only",
	"tui.mutationsDisabled": "Changes are refused by NKT_ALLOW_MUTATIONS=false",
	"tui.doneSuffix":        ": done",
	"tui.cancel":            "Cancel",
	"tui.execute":           "Confirm",
	"tui.readyHint":         "Ready. F5 refresh, r rescan, ? help.",
	"tui.scanningHost":      "Scanning the host…",
	"tui.scanFailed":        "scan failed: %s",
	"tui.rescanDone":        "host rescanned in %d ms, findings: %d",

	"tui.help.title":            "Help",
	"tui.help.navigation":       "Navigation",
	"tui.help.switchScreen":     "  1…9, 0       switch screen",
	"tui.help.tabNextPrev":      "  Tab / Shift+Tab   next and previous screen",
	"tui.help.tableNav":         "  ↑ ↓ PgUp PgDn     move through the table",
	"tui.help.enterDetails":     "  Enter        details for the selected row",
	"tui.help.commonActions":    "Common actions",
	"tui.help.f5Refresh":        "  F5           refresh the current screen's data",
	"tui.help.rRescan":          "  r            rescan the whole host",
	"tui.help.qmarkHelp":        "  ?            this help",
	"tui.help.qQuit":            "  q            quit",
	"tui.help.screensHeading":   "Screens",
	"tui.help.configsKeys":      "  Configs       e edit, d diff against a version, v history, u rollback",
	"tui.help.servicesKeys":     "  Services      s start, x stop, t restart, l reload, c validate config",
	"tui.help.firewallKeys":     "  Firewall      a add rule, x delete rule",
	"tui.help.certsKeys":        "  Certificates  Enter show file, g issue self-signed",
	"tui.help.availabilityKeys": "  Availability  p check now, space pause and resume",
	"tui.help.auditNote":        "Every change is logged under the name %s.",
	"tui.help.mutationsNote":    "If NKT_ALLOW_MUTATIONS=false is set, actions are unavailable.",

	"tui.noData":                      "no data",
	"tui.noMeasurementsInPeriod":      "No measurements in this period.",
	"tui.historyCollectedByScheduler": "History is collected by the background scheduler — start the netknownsthat service.",
	"tui.heatmapLess":                 "less",
	"tui.heatmapMore":                 "more   (max %s, ·· — no measurements)",

	"tui.justNow":    "just now",
	"tui.minutesAgo": "%d min ago",
	"tui.hoursAgo":   "%d h ago",
	"tui.daysAgo":    "%d d ago",

	"tui.severity.critical": "critical",
	"tui.severity.high":     "high",
	"tui.severity.medium":   "medium",
	"tui.severity.low":      "low",
	"tui.severity.info":     "info",

	"tui.configs.title":                 "Configs",
	"tui.configs.colFile":               "File",
	"tui.configs.colService":            "Service",
	"tui.configs.colSize":               "Size",
	"tui.configs.colModified":           "Modified",
	"tui.configs.listTitle":             "Config files",
	"tui.configs.listTitleCount":        "Config files — %d",
	"tui.configs.contentTitle":          "Content",
	"tui.configs.hints":                 "e edit · v version history · u roll back to a version",
	"tui.configs.listError":             "file list: %s",
	"tui.configs.readError":             "could not read: %s",
	"tui.configs.openError":             "could not open the file: %s",
	"tui.configs.editorTitle":           "%s — Ctrl+S save, Esc cancel",
	"tui.configs.noteLabel":             "Edit note",
	"tui.configs.applyLabel":            "Reload the service after saving",
	"tui.configs.unchanged":             "File unchanged — nothing to save.",
	"tui.configs.saving":                "Validating and saving %s",
	"tui.configs.rolledBackSuffix":      " — the file was rolled back to its previous state",
	"tui.configs.saved":                 "%s saved, version #%d",
	"tui.configs.notValidatedSuffix":    " (config validation isn't available for this service)",
	"tui.configs.appliedSuffix":         ", service reloaded",
	"tui.configs.confirmDiscard":        "Unsaved edits. Close the editor and lose them?",
	"tui.configs.emptyHistory":          "No history yet: this file has never been edited through this app.",
	"tui.configs.colVersion":            "#",
	"tui.configs.colWhen":               "When",
	"tui.configs.colWho":                "Who",
	"tui.configs.colEvent":              "Event",
	"tui.configs.colNote":               "Note",
	"tui.configs.versionsTitle":         "Version history — Enter shows the diff, Esc closes",
	"tui.configs.rollbackTitle":         "Rollback — Enter restores the selected version, Esc closes",
	"tui.configs.versionMatchesCurrent": "Version #%d matches the current file.",
	"tui.configs.diffTitle":             "Diff: version #%d vs. the current file",
	"tui.configs.confirmRollback":       "Restore version #%d from %s?\n\nThe file's current content will be replaced.",
	"tui.configs.rollingBack":           "Restoring version #%d",

	"tui.overview.attentionTitle":       "What needs attention",
	"tui.overview.colService":           "Service",
	"tui.overview.colState":             "State",
	"tui.overview.colAutostart":         "Autostart",
	"tui.overview.colMemory":            "Memory",
	"tui.overview.servicesTitle":        "Services",
	"tui.overview.availabilityTitle":    "Availability",
	"tui.overview.title":                "Overview",
	"tui.overview.hints":                "Enter service details",
	"tui.overview.statusReadFailed":     "could not read host state",
	"tui.overview.tileAttentionLabel":   "Need attention",
	"tui.overview.tileAttentionNote":    "critical %d, high %d",
	"tui.overview.tileListenersLabel":   "Listeners declared",
	"tui.overview.tileListenersNote":    "public %d, with TLS %d",
	"tui.overview.tileContainersLabel":  "Containers",
	"tui.overview.tileContainersNote":   "docker networks: %d",
	"tui.overview.tileUptimeNote":       "targets %d: up %d, down %d",
	"tui.overview.tileUptimeNoDataNote": "targets %d, no checks yet",
	"tui.overview.tileUptime24hLabel":   "Availability, 24h",
	"tui.overview.noFindings":           "No problems found.",
	"tui.overview.moreFindings":         "…%d more, see the Findings screen",
	"tui.overview.packetsSuffix":        "%s packets",
	"tui.overview.rulesTotal":           "rules total: %d",
	"tui.overview.targetsDownSummary":   "targets %d, currently down %s",
	"tui.overview.noOutages24h":         "no outages recorded in the last 24h",
	"tui.overview.recentOutages":        "recent outages:",

	"tui.findings.colSeverity":      "Severity",
	"tui.findings.colRule":          "Rule",
	"tui.findings.colObject":        "Object",
	"tui.findings.colWhatsWrong":    "What's wrong",
	"tui.findings.detailsTitle":     "Details",
	"tui.findings.title":            "Findings",
	"tui.findings.filterAll":        "all",
	"tui.findings.filterHintPrefix": "f filter: ",
	"tui.findings.titleWithCount":   "Findings — showing %d of %d",
	"tui.findings.noneMatchFilter":  "Nothing matches the selected filter.",
	"tui.findings.suggestionLabel":  "What to do: ",
	"tui.findings.ruleServiceLine":  "rule %s · service %s",
	"tui.findings.objectSuffix":     "· object %s",
	"tui.findings.fileLabel":        "file ",

	"tui.map.treeTitle":         "Network resource map",
	"tui.map.nodeTitle":         "Node",
	"tui.map.title":             "Map",
	"tui.map.hints":             "Enter collapse and expand the branch",
	"tui.map.sectionPublic":     "Reachable from outside",
	"tui.map.sectionInternal":   "Internal only",
	"tui.map.sectionContainers": "Containers",
	"tui.map.selectNodeHint":    "Select a node to see its details.",
	"tui.map.stateLabel":        "state: ",
	"tui.map.findingsSummary":   "findings: %d (worst: %s)",
	"tui.map.leadsTo":           "leads to: ",

	"tui.services.colType":               "Type",
	"tui.services.colName":               "Name",
	"tui.services.colState":              "State",
	"tui.services.colDetails":            "Details",
	"tui.services.colPortsMemory":        "Ports and memory",
	"tui.services.selectedPanelTitle":    "Selected object",
	"tui.services.title":                 "Services",
	"tui.services.hints":                 "s start · x stop · t restart · l reload · c validate config",
	"tui.services.actionUnavailable":     "“%s” not available for %s",
	"tui.services.validatingConfig":      "Validating config for %s",
	"tui.services.validationUnavailable": "validation isn't available for this service",
	"tui.services.configRejected":        "config rejected: %s",
	"tui.services.confirmAction":         "Run “%s” for %s “%s”?",
	"tui.services.kindUnit":              "service",
	"tui.services.kindContainer":         "container",
	"tui.services.kindPodman":            "Podman container",
	"tui.services.kindLXD":               "LXD instance",
	"tui.services.kindVM":                "virtual machine",
	"tui.services.containerActionDone":   "container %s: %s done",
	"tui.services.podmanActionDone":      "podman container %s: %s done",
	"tui.services.lxdActionDone":         "lxd instance %s: %s done",
	"tui.services.vmActionDone":          "VM %s: %s done",
	"tui.services.actionDone":            "%s: %s done",
	"tui.services.simulatedSuffix":       " (simulated, snapshot mode)",
	"tui.services.notInstalled":          "not installed on the host",
	"tui.services.tableTitle":            " Services and containers — %d ",
	"tui.services.noPortsPublished":      "publishes no ports",
	"tui.services.unitSuffix":            " · unit %s",
	"tui.services.stateLineUnit":         " state: %s %s   autostart: %s   restarts: %d\n",
	"tui.services.runningSince":          " running since %s\n",
	"tui.services.configFilesCount":      " config files (%d): ",
	"tui.services.availableActions":      " available actions: %s",
	"tui.services.stateBasic":            " state: %s   %s\n",
	"tui.services.podLabel":              " pod: %s\n",
	"tui.services.portsPrefix":           " ports: ",
	"tui.services.stateArch":             " state: %s   architecture: %s\n",
	"tui.services.ipv4Prefix":            " IPv4: ",
	"tui.services.ipv4NoData":            " IPv4: no data",
	"tui.services.stateVCPUMem":          " state: %s   vCPU: %d   memory: %s\n",
	"tui.services.persistentAutostart":   " persistent domain: %s   autostart: %s\n",
	"tui.services.disksPrefix":           " disks: ",
	"tui.services.networksPrefix":        " networks: ",
	"tui.services.projectServiceFile":    " project %s, service %s, file %s\n",
	"tui.services.runningOutsideCompose": "running outside the compose files",
	"tui.services.declaredNotRunning":    "declared in compose but not running",

	"tui.firewall.colNumber":           "#",
	"tui.firewall.colRuleSource":       "Rule source",
	"tui.firewall.colChain":            "Chain",
	"tui.firewall.colAction":           "Action",
	"tui.firewall.colPort":             "Port",
	"tui.firewall.colFrom":             "From",
	"tui.firewall.colPackets":          "Packets",
	"tui.firewall.colBytes":            "Bytes",
	"tui.firewall.statusPanelTitle":    "Firewall status",
	"tui.firewall.hints":               "a add rule · x delete ufw rule",
	"tui.firewall.onlyUfwDeletable":    "Only ufw rules can be deleted — iptables and docker rules change outside this interface",
	"tui.firewall.confirmDelete":       "Delete ufw rule #%d?\n\n%s",
	"tui.firewall.deletingRule":        "Deleting ufw rule #%d",
	"tui.firewall.ruleDeleted":         "rule deleted: %s",
	"tui.firewall.fieldProtocol":       "Protocol",
	"tui.firewall.fieldSource":         "Source (IP or CIDR, empty = anywhere)",
	"tui.firewall.fieldComment":        "Comment",
	"tui.firewall.addButton":           "Add",
	"tui.firewall.addingRule":          "Adding rule %s %d/%s",
	"tui.firewall.ruleAdded":           "rule added: %s",
	"tui.firewall.newRuleFormTitle":    " New ufw rule ",
	"tui.firewall.tableTitle":          " Rules — ufw %d, packet filter %d ",
	"tui.firewall.defaultZonePrefix":   "default zone: ",
	"tui.firewall.ufwRulesUnavailable": "ufw rule list unavailable: %s",
	"tui.firewall.packetsBytes":        "%s packets, %s",
	"tui.firewall.openSockets":         "\n open sockets on the host: %d",
	"tui.firewall.any":                 "any",

	"tui.monitor.availability.colResource":                 "Resource",
	"tui.monitor.availability.colAddress":                  "Address",
	"tui.monitor.availability.colNow":                      "Now",
	"tui.monitor.availability.colUptime24h":                "Uptime 24h",
	"tui.monitor.availability.colLatency":                  "Latency",
	"tui.monitor.availability.colChecks":                   "Checks",
	"tui.monitor.availability.downtimeByHourTitle":         "Downtime by hour of week",
	"tui.monitor.availability.title":                       "Availability",
	"tui.monitor.availability.hints":                       "p check now · space pause · w period: ",
	"tui.monitor.windowDay":                                "24h",
	"tui.monitor.windowWeek":                               "7 days",
	"tui.monitor.windowTwoWeeks":                           "14 days",
	"tui.monitor.windowMonth":                              "30 days",
	"tui.monitor.availability.checking":                    "Checking %s",
	"tui.monitor.availability.unreachable":                 "%s is unreachable: %s",
	"tui.monitor.availability.respondsIn":                  "%s responds in %s",
	"tui.monitor.availability.resuming":                    "resuming checks",
	"tui.monitor.availability.pausing":                     "pausing checks",
	"tui.monitor.availability.resumingFor":                 "resuming checks for %s",
	"tui.monitor.availability.pausingFor":                  "pausing checks for %s",
	"tui.monitor.availability.stateUp":                     "up",
	"tui.monitor.availability.stateDown":                   "down",
	"tui.monitor.availability.tableTitle":                  "Monitored resources — %d",
	"tui.monitor.availability.downtimeScaleLabel":          "downtime",
	"tui.monitor.availability.downtimeByHourTitleWindowed": "Downtime by hour of week — %s",
	"tui.monitor.availability.sourceLabel":                 " source: ",
	"tui.monitor.availability.checksLabel":                 "   checks in 24h: ",
	"tui.monitor.availability.failuresLabel":               "   failures: ",
	"tui.monitor.availability.lastError":                   "last error: %s",
	"tui.monitor.availability.lastCheckLabel":              " last check: ",
	"tui.monitor.availability.uptimeLabel":                 " uptime       ",
	"tui.monitor.availability.latencyLabel":                " latency      ",
	"tui.monitor.availability.byHours":                     "by hour",
	"tui.monitor.availability.outagesFor":                  "outages in %s:",
	"tui.monitor.availability.andMore":                     "…%d more",

	"tui.monitor.usage.dockerNetTraffic":    "Container network traffic",
	"tui.monitor.usage.dockerCPU":           "Container CPU",
	"tui.monitor.usage.dockerMemory":        "Container memory",
	"tui.monitor.usage.firewallTraffic":     "Firewall rule traffic",
	"tui.monitor.usage.nginxRequests":       "nginx requests",
	"tui.monitor.usage.nginx5xxErrors":      "nginx 5xx errors",
	"tui.monitor.usage.haproxyRequests":     "haproxy requests",
	"tui.monitor.usage.trendTitle":          "Trend",
	"tui.monitor.usage.topTitle":            "Top consumers",
	"tui.monitor.usage.scheduleTitle":       "Usage schedule",
	"tui.monitor.usage.title":               "Usage",
	"tui.monitor.usage.metricLabel":         "m metric: ",
	"tui.monitor.usage.periodLabel":         "  w period: ",
	"tui.monitor.usage.stepHour":            "hour",
	"tui.monitor.usage.stepDay":             "day",
	"tui.monitor.usage.noDataLine1":         "No data for this period. Metrics are collected by the background scheduler — ",
	"tui.monitor.usage.noDataLine2":         "start the netknownsthat service, or press r to scan.",
	"tui.monitor.usage.totalPeakPointsStep": "total %s   peak %s   points %d   step %s",
	"tui.monitor.usage.fixturesWarning":     "snapshot mode: values are synthetic, not measured",
	"tui.monitor.usage.noDataInPeriod":      "No data for this period.",
	"tui.monitor.usage.topTitleWithMetric":  "Top consumers — %s",
	"tui.monitor.usage.loadScaleLabel":      "load",

	"tui.monitor.audit.colAction":           "Action",
	"tui.monitor.audit.colTarget":           "Target",
	"tui.monitor.audit.colResult":           "Result",
	"tui.monitor.audit.colDetails":          "Details",
	"tui.monitor.audit.tableTitle":          "Action log",
	"tui.monitor.audit.jobsTitle":           "Background jobs",
	"tui.monitor.audit.title":               "Log",
	"tui.monitor.audit.hints":               "Enter full entry text",
	"tui.monitor.audit.userLabel":           "user:",
	"tui.monitor.audit.targetLabel":         "target:      ",
	"tui.monitor.audit.resultLabel":         "result:   ",
	"tui.monitor.audit.entryTitle":          "Log entry",
	"tui.monitor.audit.tableTitleWithCount": "Action log — %d entries",
	"tui.monitor.audit.schedulerNote1":      "The scheduler collects history only while the netknownsthat service is running.",
	"tui.monitor.audit.schedulerNote2":      "The terminal interface reads the same database and doesn't collect anything itself.",
	"tui.monitor.audit.intervalsLabel":      "intervals:",
	"tui.monitor.audit.probesLabel":         "probes",
	"tui.monitor.audit.metricsLabel":        "metrics",
	"tui.monitor.audit.inventoryLabel":      "inventory",
	"tui.monitor.audit.autoRenewLabel":      "auto-renew:",
	"tui.monitor.audit.autoRenewTemplate":   "every %s renews certbot certificates within %d days of expiry",

	"tui.certs.colSites":                    "Sites",
	"tui.certs.colExpires":                  "Expires",
	"tui.certs.colRemaining":                "Remaining",
	"tui.certs.colKey":                      "Key",
	"tui.certs.colIssuer":                   "Issuer",
	"tui.certs.colAutoRenew":                "Auto-renew",
	"tui.certs.detailTitle":                 "Certificate",
	"tui.certs.scheduleTitle":               "Expiry schedule",
	"tui.certs.title":                       "Certificates",
	"tui.certs.hints":                       "Enter show file · g issue self-signed · r renew via certbot · c build PEM for haproxy",
	"tui.certs.formNames":                   "Names, comma-separated",
	"tui.certs.formService":                 "Service",
	"tui.certs.formKeyBits":                 "Key length",
	"tui.certs.formDays":                    "Validity, days",
	"tui.certs.createButton":                "Create",
	"tui.certs.generatingSelfSigned":        "Generating self-signed certificate",
	"tui.certs.certCreatedTitle":            "Certificate created",
	"tui.certs.certValidUntil":              " %s\n valid until %s\n\n",
	"tui.certs.configNotAddedHint":          "The file has not been added to any configuration yet — paste it through the editor (Configs screen):\n\n%s\n",
	"tui.certs.certCreatedStatus":           "certificate created, fingerprint %s…",
	"tui.certs.generateFormTitle":           "New self-signed certificate",
	"tui.certs.lineageExpiryUnknown":        "%s — expiry unknown",
	"tui.certs.lineageExpiredAgo":           "%s — expired %d days ago",
	"tui.certs.lineageExpiresToday":         "%s — expires today",
	"tui.certs.lineageDaysLeft":             "%s — %d days",
	"tui.certs.letsencryptReadError":        "Could not read /etc/letsencrypt/live: %s",
	"tui.certs.noLineagesFound":             "No lineages found in /etc/letsencrypt/live",
	"tui.certs.newFileOption":               "— new file —",
	"tui.certs.formTargetPath":              "Write to",
	"tui.certs.combineButton":               "Build",
	"tui.certs.combiningPEM":                "Building PEM for haproxy",
	"tui.certs.overwrittenNoInsertNeeded":   "File %s overwritten, haproxy reloaded its configuration — nothing to paste in.\n",
	"tui.certs.pemCreatedTitle":             "PEM built",
	"tui.certs.pemCreatedStatus":            "PEM built, fingerprint %s…",
	"tui.certs.combineFormTitle":            "Build PEM for haproxy from certbot",
	"tui.certs.notManagedByCertbot":         "certbot does not manage this certificate — nothing to renew",
	"tui.certs.confirmRenew":                "Run certbot renew --cert-name %s?",
	"tui.certs.confirmRenewDerivedNote":     "\n\nThis is a copy of the certificate from %s — the original will be renewed, and this copy will be automatically rebuilt from the new certificate and key, after which the service will be reloaded.",
	"tui.certs.starting":                    "Starting…",
	"tui.certs.renewProgressTitle":          "Renewing %s — Esc to hide (continues in background)",
	"tui.certs.renewError":                  "Error: %s",
	"tui.certs.renewDone":                   "Done.",
	"tui.certs.unreadable":                  "unreadable",
	"tui.certs.expiredDaysAgo":              "expired %d days ago",
	"tui.certs.expiresToday":                "expires today",
	"tui.certs.daysLeft":                    "%d days",
	"tui.certs.scheduleNoData":              "Nothing to show.",
	"tui.certs.scheduleHeader":              " runway to expiry, scale — one year\n\n",
	"tui.certs.fileUnreadable":              "file unreadable",
	"tui.certs.scheduleThresholds":          " thresholds: %d days — warning, %d days — urgent",
	"tui.certs.noSslCertificates":           "No ssl_certificate found in the parsed configurations.",
	"tui.certs.titleCount":                  "Certificates — %d",
	"tui.certs.certErrorLabel":              "error: %s",
	"tui.certs.detailValidity":              " valid: %s — %s   %s\n",
	"tui.certs.issuerLabel":                 " issuer:  ",
	"tui.certs.subjectLabel":                " subject: ",
	"tui.certs.keyLabel":                    " key: ",
	"tui.certs.keyBitsFormat":               "%s %d bit",
	"tui.certs.sigLabel":                    "   signature: ",
	"tui.certs.chainLabel":                  " chain: ",
	"tui.certs.chainCountFormat":            "%d certificate(s)",
	"tui.certs.selfSignedLabel":             "self-signed",
	"tui.certs.servesLabel":                 " serves: ",
	"tui.certs.renewalLabel":                "renewal: %s",
	"tui.certs.derivedCopyPrefix":           "certbot copy, ",
	"tui.certs.renewalAutomatic":            "automatic",
	"tui.certs.renewalConfiguredNotRunning": "configured but not running",
	"tui.certs.renewalCertbotRecordLost":    "certbot record lost",
	"tui.certs.renewalManual":               "manual",
}
