package msgs

// Тексты бота Telegram хаба — отдельным файлом.
func init() {
	for k, v := range enTelegramCatalog {
		enCatalog[k] = v
	}
}

// #nosec G101 -- тексты сообщений (ключи вроде auth.tokenInvalid), а не учётные данные.
var enTelegramCatalog = map[string]string{
	"tg.unknownChat":           "The hub does not know this chat. Chat number: %d; add it in \"Alerts\" → \"Telegram bot\".",
	"tg.helpRead":              "Commands:\n/status — host summary\n/hosts — hosts\n/alerts — latest alerts\n/pipelines — pipelines\n/id — chat and your number",
	"tg.helpAdmin":             "Commands:\n/status — host summary\n/hosts — hosts\n/alerts — latest alerts\n/pipelines — pipelines\n/deploy <pipeline> — deploy (with confirmation)\n/dryrun <pipeline> — dry run\n/ban <IP> and /unban <IP> — on every host with fail2ban (with confirmation)\n/id — chat and your number",
	"tg.chatID":                "Chat: %d, you: %d",
	"tg.denied":                "Actions are not available here: this needs a chat with the admin role (and you on the allowed list, if one is set).",
	"tg.noPipeline":            "No pipeline \"%s\"; /pipelines shows names and numbers.",
	"tg.confirmDeploy":         "Deploy \"%s\"?",
	"tg.btnDeploy":             "🚀 Deploy",
	"tg.btnCancel":             "Cancel",
	"tg.banUsage":              "Like this: /ban 198.51.100.7 (or a subnet).",
	"tg.confirmBan":            "Ban %s on every host with fail2ban?",
	"tg.confirmUnban":          "Unban %s on every host with fail2ban?",
	"tg.btnBan":                "🚫 Ban",
	"tg.btnUnban":              "Unban",
	"tg.unknownCommand":        "Unknown command; see /help.",
	"tg.cancelled":             "Cancelled.",
	"tg.expired":               "The confirmation has expired or is not yours; repeat the command.",
	"tg.deployStarted":         "Deployment \"%s\" started as job %d. I will send the outcome.",
	"tg.jobStarted":            "Job %d started. I will send the outcome.",
	"tg.dryStarted":            "Dry run of \"%s\" is job %d. I will send the outcome.",
	"tg.status":                "🔴 %d · 🟠 %d · 🟡 %d · 🟢 %d · ⚪ %d\nFindings: %d critical, %d high, %d medium",
	"tg.noFindings":            "no findings",
	"tg.findings":              "findings: %d crit., %d high, %d med.",
	"tg.noHost":                "No host %d.",
	"tg.hostUp":                "up",
	"tg.hostDown":              "unreachable",
	"tg.noAlerts":              "No alerts.",
	"tg.kind.unreachable":      "unreachable",
	"tg.kind.recovered":        "recovered",
	"tg.kind.problems":         "new findings",
	"tg.kind.resolved":         "findings resolved",
	"tg.kind.job-failed":       "job failed",
	"tg.kind.rebooted":         "rebooted",
	"tg.kind.bans":             "new bans",
	"tg.kind.deploy-succeeded": "deployment succeeded",
	"tg.kind.deploy-failed":    "deployment failed",
	"tg.noPipelines":           "No pipelines.",
	"tg.noJob":                 "No job %d.",
	"tg.job":                   "Job %d · %s — %s",
	"tg.jobStatus.queued":      "queued",
	"tg.jobStatus.running":     "running",
	"tg.jobStatus.succeeded":   "✅ done",
	"tg.jobStatus.failed":      "❌ failed",
	"tg.jobStatus.canceled":    "canceled",
	"tg.jobStatus.interrupted": "interrupted",
	"tg.btnOverview":           "🔎 Overview",
	"tg.btnFindings":           "⚠️ Findings",
	"tg.btnLog":                "📜 Log",
	"tg.btnRetry":              "🔁 Retry",
	"tg.badToken":              "A bot token looks like 123456789:AA… (from @BotFather)",
	"tg.tokenRejected":         "Telegram rejected the token: %s",
	"tg.tooMany":               "Up to 50 chats and 200 people",
	"tg.noToken":               "Set the bot token first",
	"tg.noChat":                "Chat %d is not on the list",
	"tg.test":                  "A test message from the nkt bot (sent by %s).",
	"slack.helpRead":           "Commands: /nkt status — summary, /nkt hosts — hosts, /nkt alerts — alerts, /nkt pipelines — pipelines, /nkt id — channel and your id.",
	"slack.helpAdmin":          "Commands: /nkt status, /nkt hosts, /nkt alerts, /nkt pipelines; /nkt deploy <pipeline> and /nkt ban|unban <IP> with a confirmation button; /nkt dryrun <pipeline>; /nkt id.",
	"slack.unknownChannel":     "The hub does not know this channel: %s; add it in \"Alerts\" → \"Slack\".",
	"slack.ids":                "Channel: %s, you: %s",
	"slack.badToken":           "A Slack bot token looks like xoxb-…",
	"slack.tokenRejected":      "Slack rejected the token: %s",
	"slack.badSigning":         "A Slack signing secret is 32 hex characters (Basic Information → Signing Secret)",
	"slack.badChannel":         "Not a Slack channel id: %q (like C0123ABCD)",
	"slack.badUser":            "Not a Slack user id: %q (like U0123ABCD)",
	"slack.incomplete":         "Both the bot token and the signing secret are needed",
	"slack.noChannel":          "Channel %s is not on the list",
	"tg.yesterday":             "yesterday",
	"tg.findingsCount":         "Serious findings: %d (was %d)",
	"tg.andMore":               "…and %d more",
	"tg.hostsHead":             "Hosts: %d",
	"tg.hostError":             "error: %s",
	"tg.hostInstalling":        "installing",
	"tg.hostNoData":            "no data",
	"tg.badTimezone":           "Unknown time zone: %q (expected like Europe/Moscow)",
	"tg.overviewHead":          "overview",
	"tg.findingsHead":          "findings",
}
