package msgs

// ruCLICatalog — строки командной строки nkt (cmd/nkt, ключи cli.*): справка,
// флаги, отчёт scan, passwd/users, hub delete/import. Язык выбирается по
// локали терминала (cmd/nkt/cli_lang.go).
func init() {
	for k, v := range ruCLICatalog {
		ruCatalog[k] = v
	}
}

// #nosec G101 -- тексты сообщений командной строки (ключи вроде cli.passwd.prompt), а не учётные данные.
var ruCLICatalog = map[string]string{
	"cli.flag.verbose":               "подробный лог",
	"cli.flag.scan":                  "разовая проверка и выход",
	"cli.flag.version":               "показать версию и выйти",
	"cli.flag.random":                "сгенерировать пароль вместо ввода",
	"cli.flag.role":                  "роль создаваемой учётной записи: admin или viewer",
	"cli.flag.yes":                   "в hub delete: не спрашивать подтверждения",
	"cli.flag.export":                "в hub delete: сохранить сюда экспорт хостов с ключом перед удалением",
	"cli.flag.noExport":              "в hub delete: не предлагать и не делать экспорт перед удалением",
	"cli.flag.file":                  "в hub import: путь к файлу экспорта (обычному или зашифрованному паролем)",
	"cli.usage":                      "NetKnownsThat %s — карта сетевых ресурсов и проверка конфигураций хоста.\n\nИспользование:\n  nkt [serve]         запустить веб-дашборд и фоновый сбор данных (по умолчанию)\n  nkt tui             терминальный интерфейс: то же самое без браузера\n  nkt scan            разовая проверка, отчёт в stdout, код 2 при критичных находках\n  nkt hub             управляющий центр: установка и проксирование nkt на других хостах по SSH\n  nkt hub delete      безвозвратно стереть данные и ключи хаба (сервис и бинарник остаются)\n  nkt hub import -file <файл>   восстановить хосты из экспорта (обычного или с паролем)\n  nkt users           показать учётные записи веб-интерфейса\n  nkt passwd [логин]  сменить пароль (по умолчанию admin), спросит его без эха\n  nkt version         показать версию\n\nФлаги:\n  -v                  подробный лог\n  -random             в passwd: сгенерировать пароль и напечатать один раз (только в терминал)\n  -role admin|viewer  в passwd: создать учётную запись с этой ролью, если её нет\n  -yes                в hub delete: не спрашивать подтверждения\n  -export <файл>      в hub delete: сохранить сюда экспорт хостов с ключом перед удалением\n  -no-export          в hub delete: не предлагать и не делать экспорт перед удалением\n  -file <файл>        в hub import: путь к файлу экспорта\n\nПримеры:\n  sudo nkt passwd                     сменить пароль администратора\n  sudo nkt passwd ops -role viewer    завести учётку только на чтение\n  sudo nkt passwd -random             выдать новый случайный пароль admin\n  sudo nkt hub delete                 удалить хаб: спросит про экспорт и подтверждение\n  sudo nkt hub delete -export a.json  удалить хаб, предварительно сохранив экспорт в a.json\n  sudo nkt hub import -file a.json    восстановить хосты из ранее сохранённого экспорта\n\nНастройка — через переменные окружения NKT_*, см. deploy/nkt.env.example.\n",
	"cli.unknownCommand":             "неизвестная команда %q",
	"cli.scan.host":                  "Хост:       %s (%s, режим %s)\n",
	"cli.scan.took":                  "Скан:       %s за %d мс\n",
	"cli.scan.found":                 "Найдено:    %d слушателей в конфигах, %d пулов, %d контейнеров, %d правил firewall\n\n",
	"cli.scan.sourceError":           "ОШИБКА: %s",
	"cli.scan.sourceUnavailable":     "недоступен",
	"cli.scan.problems":              "\nПроблемы: critical=%d high=%d medium=%d low=%d info=%d\n",
	"cli.scan.finding":               "\n[%s] %s\n    объект: %s\n    %s\n",
	"cli.dataDir":                    "каталог данных %s: %v\nхаб работает от пользователя uid %d; отдайте ему каталог данных, например:\n  docker run --rm -v <том>:/data alpine chown -R 1000:1000 /data",
	"cli.dataDirNotWritable":         "каталог данных %s не доступен на запись: %v\nхаб работает от пользователя uid %d; отдайте ему каталог данных, например:\n  docker run --rm -v <том>:/data alpine chown -R 1000:1000 /data",
	"cli.users.none":                 "Учётных записей нет. Запустите nkt — администратор создастся при первом старте.",
	"cli.users.colLogin":             "ЛОГИН",
	"cli.users.colRole":              "РОЛЬ",
	"cli.users.colState":             "СОСТОЯНИЕ",
	"cli.users.colCreated":           "СОЗДАН",
	"cli.users.colLast":              "ПОСЛЕДНИЙ ВХОД",
	"cli.users.active":               "активна",
	"cli.users.disabled":             "отключена",
	"cli.users.never":                "не входил",
	"cli.passwd.noAccount":           "учётной записи %q нет. Существующие: nkt users. Чтобы создать новую, укажите роль: nkt passwd %s -role admin",
	"cli.passwd.badRole":             "роль должна быть admin или viewer, получено %q",
	"cli.passwd.tooShort":            "пароль должен быть не короче %d символов",
	"cli.passwd.randomNeedsTerminal": "-random печатает пароль только в терминал, а вывод перенаправлен — запустите команду в терминале (в docker — без -T) или задайте пароль без -random",
	"cli.passwd.createFailed":        "создание учётной записи: %v",
	"cli.passwd.created":             "Создана учётная запись %s с ролью %s.\n",
	"cli.passwd.setFailed":           "смена пароля: %v",
	"cli.passwd.roleFailed":          "смена роли: %v",
	"cli.passwd.roleChanged":         "Роль %s изменена на %s.\n",
	"cli.passwd.changed":             "Пароль %s изменён, все его сессии завершены.\n",
	"cli.passwd.generated":           "\n  логин:  %s\n  пароль: %s\n\n  Сохраните пароль: он больше нигде не отображается.\n",
	"cli.passwd.prompt":              "Новый пароль: ",
	"cli.passwordRepeat":             "Повторите пароль: ",
	"cli.passwordMismatch":           "пароли не совпадают",
	"cli.needsHubMode":               "%s требует NKT_MODE=hub, сейчас %q",
	"cli.hubKey":                     "ключ шифрования секретов хаба: %v",
	"cli.delete.canceled":            "Отменено, ничего не удалено.",
	"cli.delete.wiping":              "Стираю %s…\n",
	"cli.delete.failed":              "удаление данных хаба: %v",
	"cli.delete.done":                "Готово: ключ шифрования, база (включая SSH- и admin-секреты всех подключённых хостов), история конфигов и TLS-ключ в %s затёрты и удалены; кэш бинарников и Go-тулчейн — просто удалены (в них нет секретов, только публичный код).\nСами хосты и установленный на них nkt это не трогает — только то, что хаб о них знал.\nБинарник и systemd-юнит хаба остались на месте: `sudo systemctl start netknownsthat-hub` поднимет полностью новый хаб — новый ключ, новая учётная запись администратора.\n",
	"cli.delete.yesNeedsExport":      "с -yes нужно явно указать -export <файл> или -no-export — без терминала нечем спросить, нужен ли бэкап перед необратимым удалением",
	"cli.delete.noTerminal":          "стандартный ввод не терминал — укажите -export <файл> или -no-export явно",
	"cli.delete.askExport":           "Сохранить экспорт хостов с ключом перед удалением, для восстановления? [Y/n]: ",
	"cli.delete.askPath":             "Куда сохранить файл экспорта: ",
	"cli.delete.noPath":              "путь для экспорта не указан",
	"cli.export.warn":                "Файл экспорта — открытый JSON с ключом шифрования хаба и SSH-/admin-секретами\nвсех хостов внутри: у кого окажется файл, у того и они. НАСТОЯТЕЛЬНО\nрекомендуется зашифровать его паролем прямо сейчас, а не хранить как есть.",
	"cli.export.askPassword":         "Пароль для шифрования файла (пусто — не шифровать, не рекомендуется): ",
	"cli.export.prepare":             "подготовка экспорта: %v",
	"cli.export.marshal":             "сериализация экспорта: %v",
	"cli.export.encrypt":             "шифрование экспорта паролем: %v",
	"cli.export.write":               "запись %s: %v",
	"cli.export.savedEncrypted":      "Экспорт с ключом зашифрован паролем и сохранён в %s (%d хостов). Восстановить его обратно — `nkt hub import -file %s`. Без пароля файл бесполезен, но храните пароль отдельно от файла (не рядом, не в той же переписке) — иначе шифрование ничего не даёт.\n",
	"cli.export.savedPlain":          "\n!!! Экспорт с ключом сохранён БЕЗ ШИФРОВАНИЯ в %s (%d хостов). !!!\nЭто открытый файл: ключ шифрования хаба и SSH-/admin-секреты всех хостов читаются из него напрямую, без пароля. Храните и передавайте его так же осторожно, как файл с паролями, и удалите сразу после того, как он больше не нужен.\n\n",
	"cli.delete.confirm":             "\nВНИМАНИЕ: необратимо сотрёт (с затиранием содержимого, не просто rm) ключ шифрования, базу хаба — включая SSH- и admin-секреты ВСЕХ подключённых хостов — кэш бинарников и историю конфигов в %s.\nСами управляемые хосты и nkt на них не трогает — только то, что этот хаб о них знал.\n\nНаберите «%s», чтобы продолжить: ",
	"cli.delete.word":                "удалить",
	"cli.delete.shred":               "затирание %s: %v",
	"cli.delete.remove":              "удаление %s: %v",
	"cli.import.noFile":              "укажите файл экспорта: nkt hub import -file <файл>",
	"cli.import.read":                "чтение %s: %v",
	"cli.import.section":             "%s: добавлено %d, заменено %d, пропущено (уже есть) %d\n",
	"cli.import.error":               "  ошибка: %s\n",
	"cli.import.errors":              "ошибок при импорте: %d",
	"cli.import.noTerminal":          "файл зашифрован паролем, а стандартный ввод не терминал — задайте NKT_HUB_EXPORT_PASSWORD",
	"cli.import.askPassword":         "Файл зашифрован паролем. Пароль: ",
}
