package msgs

// Сообщения раздела fail2ban (хост и хаб) — отдельным файлом, как и TUI.
func init() {
	for k, v := range ruFail2banCatalog {
		ruCatalog[k] = v
	}
}

var ruFail2banCatalog = map[string]string{
	"f2b.alreadyInstalled":               "fail2ban уже установлен",
	"f2b.configTestFailed":               "fail2ban не примет конфигурацию с шаблоном: %s",
	"f2b.configBrokenBefore":             "конфигурация fail2ban на хосте сломана ещё до шаблона — сначала исправьте её: %s",
	"f2b.jailsLost":                      "после перезагрузки fail2ban не работают джейлы %s — файлы шаблона откачены. Журнал fail2ban:\n%s",
	"finding.f2bConfigBroken.title":      "Конфигурация fail2ban не проходит проверку",
	"finding.f2bConfigBroken.detail":     "fail2ban-client -t: %s. Сервер ещё работает со старыми настройками, но следующая перезагрузка или перезапуск fail2ban упадёт.",
	"finding.f2bConfigBroken.suggestion": "Исправьте джейл из ошибки: поставьте недостающий фильтр или выключите джейл (enabled = false) в «Конфигурациях» → fail2ban.",
	"f2b.noteOwnRefresh":                 "nkt: устаревший фильтр ручного джейла заменён текущим",
	"f2b.notInstalled":                   "fail2ban не установлен",
	"f2b.badBanTime":                     "Срок бана — от минуты до 10 лет",
	"f2b.badIP":                          "Не адрес IPv4/IPv6: %q",
	"f2b.badJail":                        "Нет такого джейла: %q",
	"f2b.badLogPath":                     "Журнал для проверки — файл под /var/log или systemd-journal, а не %q",
	"f2b.badTemplateName":                "Имя шаблона — строчные латинские буквы, цифры, «-» и «_», до 41 символа: %q",
	"f2b.banHub":                         "%s — внешний адрес хаба: бан отрезал бы хаб от хоста",
	"f2b.banLoopback":                    "%s — локальный адрес, банить его бессмысленно",
	"f2b.banSelf":                        "%s — ваш собственный адрес: бан отрезал бы вас от хоста",
	"f2b.commandFailed":                  "fail2ban-client %s: код %d: %s",
	"f2b.configsUnavailable":             "Редактор конфигураций недоступен",
	"f2b.emptyFilter":                    "Пустой фильтр: нужна хотя бы одна строка failregex",
	"f2b.noIPs":                          "Не указано ни одного адреса",
	"f2b.tooManyIPs":                     "Слишком много адресов за раз: %d (не больше 256)",
	"f2b.noteHub":                        "Защита от самоблокировки: адрес хаба %s в ignoreip",
	"f2b.noteManual":                     "Джейл ручных банов nkt",
	"f2b.noteSetup":                      "Подготовка fail2ban nkt",
	"f2b.noteTemplate":                   "Шаблон «%s»",
	"f2b.templateDeletedNote":            "Шаблон удалён",
	"f2b.templateNoJail":                 "В тексте джейла нет секции [имя-джейла]",
	"f2b.templateNotFound":               "Шаблона %q нет",
	"f2b.templateTooLarge":               "Шаблон слишком большой (джейл и фильтр — до 64 КБ, описание — до 500 символов)",

	"finding.f2bMissing.title":            "SSH открыт наружу, а fail2ban не установлен",
	"finding.f2bMissing.detail":           "Перебор паролей SSH ничем не ограничен: каждый адрес может пробовать сколько угодно.",
	"finding.f2bMissing.suggestion":       "«fail2ban» → «Установить»: nkt поставит пакет, включит джейл sshd и добавит адрес хаба в исключения.",
	"finding.f2bStopped.title":            "fail2ban установлен, но не работает",
	"finding.f2bStopped.detail":           "Сервер fail2ban не отвечает — баны не ставятся. %s",
	"finding.f2bStopped.suggestion":       "«fail2ban» → «Подготовить» или «Сервисы» → fail2ban → журнал: чаще всего джейл ссылается на несуществующий журнал.",
	"finding.f2bNoSSHJail.title":          "fail2ban не защищает SSH",
	"finding.f2bNoSSHJail.detail":         "SSH открыт наружу, а джейла sshd среди запущенных нет.",
	"finding.f2bNoSSHJail.suggestion":     "«fail2ban» → «Шаблоны» → sshd.",
	"finding.f2bDeadJail.title":           "Джейл %s ничего не видит",
	"finding.f2bDeadJail.detail":          "Файлов журнала джейла нет на диске: %s. Джейл запущен, но банить ему не по чему.",
	"finding.f2bDeadJail.suggestion":      "Поправьте logpath джейла или переключите его на journald (backend = systemd).",
	"finding.f2bHubNotIgnored.title":      "Хаб (%s) может забанить сам себя",
	"finding.f2bHubNotIgnored.detail":     "Адреса хаба нет в ignoreip джейлов: %s. Несколько неудачных подключений хаба — и он потеряет связь с хостом.",
	"finding.f2bHubNotIgnored.suggestion": "«fail2ban» → «Подготовить»: nkt добавит адрес хаба в [DEFAULT] ignoreip. Если в джейле свой ignoreip — впишите адрес и туда.",

	"hub.newBans":            "fail2ban забанил новые адреса (%d): %s",
	"hub.f2bNoSSHConnection": "хост не сообщил SSH_CONNECTION",
	"hub.f2bBadAction":       "Неизвестное действие: %q (нужно ban или unban)",
	"hub.f2bNoHosts":         "Нет хостов с fail2ban",
	"hub.f2bJobBan":          "Бан %s на хостах (%d)",
	"hub.f2bJobUnban":        "Разбан %s на хостах (%d)",
	"hub.f2bHostGone":        "Хоста #%d больше нет — пропущен",
	"hub.f2bStep":            "Хост %s",
	"hub.f2bHostDone":        "%s: готово",
	"hub.f2bHostOld":         "%s: старая версия nkt без fail2ban — пропущен, обновите nkt",
	"hub.f2bHostNoFail2ban":  "%s: fail2ban не установлен — пропущен",
	"hub.f2bHostFailed":      "%s: ошибка: %s",
	"hub.f2bFailedCount":     "Не получилось на %d из %d хостов",
	"hub.f2bNoLocal":         "Встроенный API машины хаба недоступен",
	"hub.aiIPPrivate":        "Тип адреса: частный/локальный — это адрес внутренней сети, а не интернета.",
	"hub.aiIPPublic":         "Тип адреса: публичный (интернет).",
	"hub.aiIPReverse":        "Обратный DNS: %s",
	"hub.aiIPNoReverse":      "Обратный DNS: записи нет.",
	"hub.aiIPBannedOn":       "Забанен сейчас на %d записях (хостов с fail2ban: %d): %s",
	"hub.aiIPNotBanned":      "Сейчас не забанен ни на одном хосте (хостов с fail2ban: %d).",
	"hub.aiIPLog":            "Журнал fail2ban хоста %s за 7 дней: строк с адресом %d; события: %s. Последние:",
	"hub.aiIPNoLog":          "В журналах fail2ban хостов за 7 дней адрес не встречается (или журналы недоступны).",
	"hub.aiIPEvents":         "Упоминаний в оповещениях хаба: %d, последнее — %s.",
	"f2b.badIgnoreEntry":     "Не адрес, сеть или имя хоста: %q",
	"f2b.tooManyIgnore":      "Слишком длинный список исключений: %d (не больше 500)",
	"f2b.noteIgnore":         "Общий список исключений ignoreip",
}
