package msgs

// Выкладка compose-стеков и сайты — отдельным файлом.
func init() {
	for k, v := range ruSitesCatalog {
		ruCatalog[k] = v
	}
}

var ruSitesCatalog = map[string]string{
	"compose.badPath":          "Недопустимый путь файла стека: %q",
	"compose.badProject":       "Имя стека — строчные латинские буквы, цифры, «-» и «_»: %q",
	"compose.commandFailed":    "docker compose %s: код %d",
	"compose.configRejected":   "compose не принял описание стека: %s",
	"compose.done":             "Стек %s поднят",
	"compose.jobTitle":         "Выкладка стека %s",
	"compose.noEngine":         "На хосте нет ни docker, ни podman",
	"compose.noFile":           "Нет compose-файла стека: %q",
	"compose.stepPull":         "Образы стека %s",
	"compose.stepStatus":       "Состояние стека %s",
	"compose.stepUp":           "Подъём стека %s",
	"compose.tooLarge":         "Файлы стека слишком большие (до 4 МБ и 200 файлов)",
	"compose.waitTimeout":      "Контейнеры стека %s не поднялись за %d с",
	"site.badDomain":           "Недопустимое имя сайта: %q",
	"site.badOverride":         "Файл публикации nkt повреждён: %s",
	"site.badProxy":            "Неизвестный прокси: %q (nginx, haproxy, caddy)",
	"site.badTarget":           "Цель сайта: стек, сервис и порт контейнера",
	"site.badUpstream":         "Адрес цели — IP или localhost с портом: %q",
	"site.caddyOwnCert":        "Caddy получает и продлевает сертификат сам — certbot не нужен",
	"site.certExisting":        "Сертификат %s действует ещё %d дн. — используется он",
	"site.certNotFound":        "После выпуска сертификат для %s не найден",
	"site.done":                "Сайт %s настроен → %s",
	"site.firewallClosedSkip":  "%s: порты 80/443 похоже закрыты, открывать не просили — пропускаю",
	"site.firewallOff":         "Файрвол хоста не включён — открывать нечего",
	"site.firewallOpen":        "%s: порты 80/443 уже открыты",
	"site.firewallOpened":      "%s: открыты порты 80 и 443",
	"site.haproxyForeignBind":  "HAProxy уже слушает порт %s в своём frontend — два frontend на одном порту невозможны; добавьте backend в него вручную или освободите порт",
	"site.jobTitle":            "Сайт %s",
	"site.nginxNoConfD":        "%s не подключает conf.d/*.conf — nkt некуда положить сайт",
	"site.noCertbot":           "На хосте нет certbot — поставьте его в «Пакетах»",
	"site.noDomain":            "Не указано имя сайта",
	"site.noFreePort":          "Нет свободного локального порта 18000–18999",
	"site.notFound":            "Сайта %s на хосте нет",
	"site.noteOverride":        "Публикация сервиса для сайта %s",
	"site.noteProxy":           "Сайт %s",
	"site.noteRemoved":         "Сайт %s удалён",
	"site.portPublic":          "Сервис %s уже опубликован на порту %d всех адресов — он доступен и мимо прокси; лучше привязать его к 127.0.0.1 в compose-файле",
	"site.proxyMissing":        "%s не установлен",
	"site.proxyRejected":       "Конфигурация %s не прошла проверку и откатилась: %s",
	"site.proxyStarted":        "%s запущен",
	"site.proxyWritten":        "Записано: %s",
	"site.published":           "Сервис %s опубликован на 127.0.0.1:%d (порт контейнера %d)",
	"site.serviceMissing":      "В стеке %[2]s нет сервиса %[1]s",
	"site.stackMissing":        "Стека %s нет в /srv/compose",
	"site.stepCert":            "Сертификат: %s",
	"site.stepCheck":           "Проверка: %s",
	"site.stepFirewall":        "Файрвол",
	"site.stepProxy":           "Прокси: %s",
	"site.stepTarget":          "Цель сайта",
	"site.tooManyDomains":      "Слишком много имён: %d (до 20)",
	"site.upstream":            "Прокси будет смотреть на %s",
	"compose.buildOnly":        "сервис %s собирается из исходников (build:) — укажите готовый образ (image:): выкладка берёт только готовые образы, сборка — дело CI",
	"deploy.composeBinary":     "%s — двоичный файл: файлы стека едут на хост текстом, двоичному место в образе",
	"deploy.composeFiles":      "Файлов стека: %d, стек %s, хостов: %d",
	"deploy.composeHostDone":   "%s: стек поднят",
	"deploy.composeHostFailed": "%s: %s — остальные хосты не тронуты",
	"deploy.composeNote":       "Конвейер %s, коммит %s",
	"deploy.composeOutside":    "%s вне каталога compose-файла %s — относительные ссылки compose на него не сработают",
	"deploy.hostUnknown":       "Хоста %q в хабе нет",
	"deploy.noHosts":           "Ни одного работающего хоста для выкладки",
	"deploy.siteFailed":        "Сайт %s не ответил по HTTPS: %s",
	"deploy.siteOK":            "Сайт %s отвечает: HTTP %d, сертификат ещё %d дн.",
	"deploy.stepCompose":       "Стек на %s",
	"hub.siteDNSMismatch":      "%s ведёт на %s, а у хоста адреса %s — выпуск сертификата, скорее всего, не пройдёт",
	"hub.siteDNSOK":            "%s → %s — это хост",
	"hub.siteExists":           "Сайт %s уже есть",
	"hub.siteHTTPSFailed":      "%s снаружи не ответил: %s (DNS мог ещё не разойтись, сервис — стартовать)",
	"hub.siteHTTPSOK":          "https://%s отвечает: HTTP %d, сертификат ещё %d дн.",
	"hub.siteInstallingProxy":  "%s не установлен — ставлю",
	"hub.siteJobTitle":         "Сайт %s",
	"hub.siteLAN":              "Имя ведёт в частную сеть — хаб видит порты изнутри, интернет может видеть иначе",
	"hub.sitePort":             "Порт %s снаружи: %s",
	"hub.sitePort80Blocked":    "Порт 80 не отвечает даже отказом — похоже, его закрывает файрвол провайдера или NAT: Let's Encrypt не дойдёт до хоста",
	"hub.siteStepDNS":          "DNS: %s",
	"hub.siteStepHTTPS":        "Проверка https://%s",
	"hub.siteStepHost":         "Настройка на %s",
	"hub.siteStepPorts":        "Порты 80 и 443 снаружи",
	"hub.siteStepProxy":        "Прокси: %s",
	"compose.checkNoSkopeo":    "podman без skopeo: наличие образа в registry не проверить",
	"compose.dockerInstalled":  "Docker с compose уже установлен: %s",
	"deploy.composeEngines":    "Стек не поднять — хосты не тронуты: %s",
	"deploy.hostNoEngine":      "%s: нет ни docker, ни podman",
	"deploy.hostNoCompose":     "%s: %s без работающего compose (%s)",
	"deploy.dryOnlyCompose":    "Сухой прогон — для конвейеров action: compose",
	"deploy.dryTitle":          "Сухой прогон %s",
	"deploy.dryNewPipeline":    "нового конвейера",
	"deploy.stepDryHosts":      "Проверка на хостах: %d",
	"deploy.stepDryResult":     "Итог",
	"deploy.dryFiles":          "Файлов стека: %d, стек %s, хостов: %d, тег %s — на хостах ничего не меняется",
	"deploy.dryOldHost":        "? %s: старая версия nkt, сухой прогон не поддерживает — пропущен",
	"deploy.dryHostError":      "✗ %s: %s",
	"deploy.dryNoEngine":       "✗ %s: нет ни docker, ни podman — «Установить Docker» у хоста",
	"deploy.dryNoCompose":      "✗ %s: %s, но compose не работает: %s",
	"deploy.dryEngine":         "%s: %s; compose %s",
	"deploy.drySimulated":      "%s: %s (фикстуры: команды не выполнялись по-настоящему)",
	"deploy.dryStackExists":    "  стек %s есть: новых файлов %d, изменится %d, без изменений %d %s",
	"deploy.dryStackNew":       "  стек %s будет создан: файлов %d",
	"deploy.dryEnv.new":        "  .env: будет создан",
	"deploy.dryEnv.changed":    "  .env: изменится",
	"deploy.dryEnv.same":       "  .env: без изменений",
	"deploy.dryEnv.keep":       "  .env: останется прежний (в конвейере не задан)",
	"deploy.dryConfigBad":      "✗ compose не принял стек: %s",
	"deploy.dryConfigOK":       "  compose config: принят; сервисы: %s",
	"deploy.dryImageRegistry":  "  образ %s: есть в registry",
	"deploy.dryImageLocal":     "  образ %s: скачан на хост",
	"deploy.dryImageLocalOnly": "  образ %s: скачан на хост, но в registry не виден (pull упадёт): %s",
	"deploy.dryImageMissing":   "✗ образ %s: в registry нет: %s",
	"deploy.dryImageUnknown":   "? образ %s: проверить не удалось: %s",
	"deploy.dryFailed":         "Сухой прогон: проблем — %d; выкладка не прошла бы",
	"deploy.dryOK":             "Сухой прогон: на всех хостах (%d) выкладка прошла бы; ничего не изменено",
}
