package msgs

// Выкладка compose-стеков и сайты — отдельным файлом.
func init() {
	for k, v := range ruSitesCatalog {
		ruCatalog[k] = v
	}
}

var ruSitesCatalog = map[string]string{
	"compose.badPath":               "Недопустимый путь файла стека: %q",
	"compose.badProject":            "Имя стека — строчные латинские буквы, цифры, «-» и «_»: %q",
	"compose.commandFailed":         "docker compose %s: код %d",
	"compose.configRejected":        "compose не принял описание стека: %s",
	"compose.done":                  "Стек %s поднят",
	"compose.jobTitle":              "Выкладка стека %s",
	"compose.noEngine":              "На хосте нет ни docker, ни podman",
	"compose.noFile":                "Нет compose-файла стека: %q",
	"compose.stepPull":              "Образы стека %s",
	"compose.stepStatus":            "Состояние стека %s",
	"compose.stepUp":                "Подъём стека %s",
	"compose.tooLarge":              "Файлы стека слишком большие (до 4 МБ и 200 файлов)",
	"compose.waitTimeout":           "Контейнеры стека %s не поднялись за %d с",
	"site.badDomain":                "Недопустимое имя сайта: %q",
	"site.badOverride":              "Файл публикации nkt повреждён: %s",
	"site.badProxy":                 "Неизвестный прокси: %q (nginx, haproxy, caddy)",
	"site.badTarget":                "Цель сайта: стек, сервис и порт контейнера",
	"site.badUpstream":              "Адрес цели — IP или localhost с портом: %q",
	"site.caddyOwnCert":             "Caddy получает и продлевает сертификат сам — certbot не нужен",
	"site.certExisting":             "Сертификат %s действует ещё %d дн. — используется он",
	"site.certNotFound":             "После выпуска сертификат для %s не найден",
	"site.done":                     "Сайт %s настроен → %s",
	"site.firewallClosedSkip":       "%s: порты 80/443 похоже закрыты, открывать не просили — пропускаю",
	"site.firewallOff":              "Файрвол хоста не включён — открывать нечего",
	"site.firewallOpen":             "%s: порты 80/443 уже открыты",
	"site.firewallOpened":           "%s: открыты порты 80 и 443",
	"site.haproxyForeignBind":       "HAProxy уже слушает порт %s в своём frontend — два frontend на одном порту невозможны; добавьте backend в него вручную или освободите порт",
	"site.jobTitle":                 "Сайт %s",
	"site.nginxNoConfD":             "%s не подключает conf.d/*.conf — nkt некуда положить сайт",
	"site.noCertbot":                "На хосте нет certbot — поставьте его в «Пакетах»",
	"site.noDomain":                 "Не указано имя сайта",
	"site.noFreePort":               "Нет свободного локального порта 18000–18999",
	"site.notFound":                 "Сайта %s на хосте нет",
	"site.noteOverride":             "Публикация сервиса для сайта %s",
	"site.noteProxy":                "Сайт %s",
	"site.noteRemoved":              "Сайт %s удалён",
	"site.portPublic":               "Сервис %s уже опубликован на порту %d всех адресов — он доступен и мимо прокси; лучше привязать его к 127.0.0.1 в compose-файле",
	"site.proxyMissing":             "%s не установлен",
	"site.proxyRejected":            "Конфигурация %s не прошла проверку и откатилась: %s",
	"site.proxyStarted":             "%s запущен",
	"site.proxyWritten":             "Записано: %s",
	"site.published":                "Сервис %s опубликован на 127.0.0.1:%d (порт контейнера %d)",
	"site.serviceMissing":           "В стеке %[2]s нет сервиса %[1]s",
	"site.stackMissing":             "Стека %s нет в /srv/compose",
	"site.stepCert":                 "Сертификат: %s",
	"site.stepCheck":                "Проверка: %s",
	"site.stepFirewall":             "Файрвол",
	"site.stepProxy":                "Прокси: %s",
	"site.stepTarget":               "Цель сайта",
	"site.tooManyDomains":           "Слишком много имён: %d (до 20)",
	"site.upstream":                 "Прокси будет смотреть на %s",
	"compose.buildOnly":             "сервис %s собирается из исходников (build:) — укажите готовый образ: image: в compose-файле или compose.images в описании конвейера (сервис: образ); сборка — дело CI",
	"deploy.composeBinary":          "%s — двоичный файл: файлы стека едут на хост текстом, двоичному место в образе",
	"deploy.composeFiles":           "Файлов стека: %d, стек %s, хостов: %d",
	"deploy.composeHostDone":        "%s: стек поднят",
	"deploy.composeHostFailed":      "%s: %s — остальные хосты не тронуты",
	"deploy.composeNote":            "Конвейер %s, коммит %s",
	"deploy.composeOutside":         "%s вне каталога compose-файла %s — относительные ссылки compose на него не сработают",
	"deploy.hostUnknown":            "Хоста %q в хабе нет",
	"deploy.noHosts":                "Ни одного работающего хоста для выкладки",
	"deploy.siteFailed":             "Сайт %s не ответил по HTTPS: %s",
	"deploy.siteOK":                 "Сайт %s отвечает: HTTP %d, сертификат ещё %d дн.",
	"deploy.stepCompose":            "Стек на %s",
	"hub.siteDNSMismatch":           "%s ведёт на %s, а у хоста адреса %s — выпуск сертификата, скорее всего, не пройдёт",
	"hub.siteDNSOK":                 "%s → %s — это хост",
	"hub.siteExists":                "Сайт %s уже есть",
	"hub.siteHTTPSFailed":           "%s снаружи не ответил: %s (DNS мог ещё не разойтись, сервис — стартовать)",
	"hub.siteHTTPSOK":               "https://%s отвечает: HTTP %d, сертификат ещё %d дн.",
	"hub.siteInstallingProxy":       "%s не установлен — ставлю",
	"hub.siteJobTitle":              "Сайт %s",
	"hub.siteLAN":                   "Имя ведёт в частную сеть — хаб видит порты изнутри, интернет может видеть иначе",
	"hub.sitePort":                  "Порт %s снаружи: %s",
	"hub.sitePort80Blocked":         "Порт 80 не отвечает даже отказом — похоже, его закрывает файрвол провайдера или NAT: Let's Encrypt не дойдёт до хоста",
	"hub.siteStepDNS":               "DNS: %s",
	"hub.siteStepHTTPS":             "Проверка https://%s",
	"hub.siteStepHost":              "Настройка на %s",
	"hub.siteStepPorts":             "Порты 80 и 443 снаружи",
	"hub.siteStepProxy":             "Прокси: %s",
	"compose.checkNoSkopeo":         "podman без skopeo: наличие образа в registry не проверить",
	"compose.dockerInstalled":       "Docker с compose уже установлен: %s",
	"deploy.composeEngines":         "Стек не поднять — хосты не тронуты: %s",
	"deploy.hostNoEngine":           "%s: нет ни docker, ни podman",
	"deploy.hostNoCompose":          "%s: %s без работающего compose (%s)",
	"deploy.dryOnlyCompose":         "Сухой прогон — для конвейеров action: compose",
	"deploy.dryTitle":               "Сухой прогон %s",
	"deploy.dryNewPipeline":         "нового конвейера",
	"deploy.stepDryHosts":           "Проверка на хостах: %d",
	"deploy.stepDryResult":          "Итог",
	"deploy.dryFiles":               "Файлов стека: %d, стек %s, хостов: %d, тег %s — на хостах ничего не меняется",
	"deploy.dryOldHost":             "? %s: старая версия nkt, сухой прогон не поддерживает — пропущен",
	"deploy.dryHostError":           "✗ %s: %s",
	"deploy.dryNoEngine":            "✗ %s: нет ни docker, ни podman — «Установить Docker» у хоста",
	"deploy.dryNoCompose":           "✗ %s: %s, но compose не работает: %s",
	"deploy.dryEngine":              "%s: %s; compose %s",
	"deploy.drySimulated":           "%s: %s (фикстуры: команды не выполнялись по-настоящему)",
	"deploy.dryStackExists":         "  стек %s есть: новых файлов %d, изменится %d, без изменений %d %s",
	"deploy.dryStackNew":            "  стек %s будет создан: файлов %d",
	"deploy.dryEnv.new":             "  .env: будет создан",
	"deploy.dryEnv.changed":         "  .env: изменится",
	"deploy.dryEnv.same":            "  .env: без изменений",
	"deploy.dryEnv.keep":            "  .env: останется прежний (в конвейере не задан)",
	"deploy.dryConfigBad":           "✗ compose не принял стек: %s",
	"deploy.dryConfigOK":            "  compose config: принят; сервисы: %s",
	"deploy.dryImageRegistry":       "  образ %s: есть в registry",
	"deploy.dryImageLocal":          "  образ %s: скачан на хост",
	"deploy.dryImageLocalOnly":      "  образ %s: скачан на хост, но в registry не виден (pull упадёт): %s",
	"deploy.dryImageMissing":        "✗ образ %s: в registry нет: %s",
	"deploy.dryImageUnknown":        "? образ %s: проверить не удалось: %s",
	"deploy.dryFailed":              "Сухой прогон: проблем — %d; выкладка не прошла бы",
	"deploy.dryOK":                  "Сухой прогон: на всех хостах (%d) выкладка прошла бы; ничего не изменено",
	"deploy.siteOneHost":            "compose.site блоком — сайт на одном хосте: укажите в hosts ровно один хост (без group)",
	"deploy.siteSetup":              "Сайт %s: прокси %s на %s",
	"deploy.siteSetupFailed":        "? Сайт %s не настроен (стек выложен): %s",
	"deploy.siteOldHostLeft":        "? Сайт %s: конфигурацию прокси на прежнем хосте убрать не удалось: %s",
	"deploy.drySiteWarn":            "? сайт: %s",
	"deploy.drySiteNoService":       "? сайт: сервиса %s нет в стеке %s (есть: %s)",
	"deploy.drySiteProxy":           "  сайт: прокси %s",
	"deploy.drySiteProxyInstall":    "  сайт: прокси %s будет установлен",
	"deploy.drySiteSame":            "  сайт %s уже настроен и не менялся — будет только проверка HTTPS",
	"deploy.drySiteWill":            "  сайт %s будет настроен: сервис %s, порт %d",
	"deploy.drySiteDNS":             "? %s → %s, а хост — %s: сертификат не выпустится, пока DNS не укажет на хост",
	"deploy.drySiteNoDNS":           "? %s не разрешается в DNS: сертификат не выпустится, пока A-запись не укажет на хост",
	"deploy.failedRemembered":       "Опрос и registry не будут повторять %s: следующая выкладка — по новому коммиту или тегу, или кнопкой",
	"deploy.envEditedOverwritten":   "? %s: .env на хосте правили вручную — перезаписан .env из «Доступа»",
	"deploy.dryEnvEdited":           "? .env на хосте правили вручную — выкладка перезапишет его .env из «Доступа»",
	"deploy.envVersionInitial":      "заданный до истории",
	"deploy.envVersionEdited":       "правка в «Доступе»",
	"deploy.envVersionCleared":      "убран в «Доступе»",
	"deploy.envVersionRestored":     "возврат версии #%d",
	"deploy.envVersionRollback":     "откат к выкладке #%d",
	"deploy.envVersionMissing":      "Версии .env #%d нет",
	"compose.removeTitle":           "Удаление стека %s",
	"compose.stepDown":              "Остановка и удаление контейнеров стека %s",
	"compose.stepDir":               "Каталог стека %s",
	"compose.removeNoStack":         "Стека в %s нет — удалять нечего",
	"compose.removeDirSkipped":      "Фикстуры: каталог %s не трогается",
	"compose.removeDirFailed":       "Каталог стека %s убрать не удалось: %s",
	"compose.removeDirDeleted":      "Каталог %s удалён вместе с данными",
	"compose.removeDirMoved":        "Каталог %s перенесён в %s (данные сохранены)",
	"compose.removed":               "Стек %s убран",
	"site.badLineage":               "Недопустимое имя сертификата: %s",
	"deploy.removeOnlyCompose":      "Удаление с хостов — для конвейеров action: compose; остальные удаляются только с хаба",
	"deploy.useRemove":              "Конвейер compose удаляется заданием: стек убирается с хостов (кнопка «Удалить»)",
	"deploy.removeTitle":            "Удаление конвейера %s",
	"deploy.removeStepSite":         "Сайт конвейера",
	"deploy.removeStepHosts":        "Стек на хостах: %d",
	"deploy.removeStepHub":          "Запись на хабе",
	"deploy.removeHostGone":         "? хоста %s на хабе уже нет — пропущен",
	"deploy.removeHost":             "%s: удаление стека %s",
	"deploy.removeHostFailed":       "%s: %s — конвейер остаётся, «Повторить»",
	"deploy.removed":                "Конвейер %s удалён с хостов и с хаба",
	"deploy.removeSite":             "Сайт %s: удаление с хоста",
	"deploy.removeSiteHostGone":     "? сайт %s: хоста на хабе уже нет — удаляется только запись",
	"deploy.removeSiteAlready":      "Сайт %s на хосте уже убран",
	"deploy.removeSiteUnpublished":  "  публикация сервиса %s на 127.0.0.1 снята",
	"deploy.removeSiteStep":         "Сайт %s: %s",
	"deploy.removeSiteCert":         "  сертификат %s удалён",
	"deploy.removeSiteCertShared":   "  сертификат нужен другому сайту — оставлен",
	"deploy.removeSiteFromPipeline": "? сайт описан в конвейере: следующая выкладка его вернёт, если блок site: не убрать",
	"hub.siteRemoveTitle":           "Удаление сайта %s",
	"hub.siteRemoveStep":            "Удаление %s с хоста",
	"hub.siteRemoved":               "Сайт %s удалён",
	"deploy.composeYAML":            "compose-файл не разобрать: %s",
	"deploy.imageServiceMissing":    "compose.images / compose.ports: сервиса %s нет в compose-файле",
	"deploy.portBound":              "  публикация %s (%s) → %s",
	"deploy.portKept":               "  публикация %s (%s): адрес задан (в compose-файле или compose.ports) — как есть; bind_force: true — заменить",
	"deploy.portSkipped":            "? порт %s (%s): в записи переменная — адрес не подставлен, укажите его в compose.ports",
	"ui.docsURLBad":                 "Адрес справки %s: нужен http:// или https://, без логина и параметров, с «/» на конце",
	"site.portNotExposed":           "Порт %d: сервис %s (образ %s) его не объявляет — объявляет %s. Поправьте site.port (порт внутри контейнера); сертификат не выпускался",
	"site.portUnverified":           "Образ %s не объявляет портов — порт сайта не проверить",
	"site.portOK":                   "Порт контейнера %d объявлен (%s)",
	"deploy.drySitePortBad":         "✗ сайт: порт %d, а сервис %s (образ %s) объявляет %s — прокси получит 502; поправьте site.port",
	"deploy.drySitePortUnknown":     "? сайт: образ %s не объявляет портов (или ещё не скачан) — порт не проверить",
	"deploy.drySitePortOK":          "  сайт: порт %d у сервиса %s объявлен",
	"hub.site502Hint":               "? 502 — прокси не достучался до сервиса %s: проверьте, что контейнер слушает порт %d (site.port — порт внутри контейнера)",
	"deploy.hostOld":                "? %s: старая версия nkt не знает полей %s — запрос повторён без них: порт сайта не проверен, ручная правка .env не отслеживается. Обновите nkt на хосте («Хосты» → «Обновить»)",
	"deploy.sitePortMissing":        "compose.site.port не задан — укажите порт внутри контейнера, который слушает образ (например, port: 80)",
	"deploy.drySitePortBadOne":      "✗ сайт: port %d, а образ %s слушает %d — укажите port: %d",
	"deploy.sitePortsMismatch":      "? сайт: compose.ports публикует у сервиса %s порт контейнера %s, а site.port — %d; сайту нужен именно site.port (публикацию сайта nkt делает сам)",
	"deploy.yamlAt":                 "описание конвейера, строка %d «%s»: %v",
	"deploy.yamlAtRaw":              "описание конвейера, строка %d «%s»: %s",
	"deploy.yamlMore":               "%v (и ещё ошибок: %d — обычно следствие первой)",
	"deploy.yamlHintKey":            "сбит отступ или у ключа сразу значение и вложенный блок (например, «site: имя» и строки под ним) — оставьте что-то одно; вложенные строки — на 2 пробела глубже родителя",
	"deploy.yamlHintColon":          "лишнее «:» в значении или сбит отступ — значение с двоеточием возьмите в кавычки (\"127.0.0.1:8080:80\")",
	"deploy.yamlHintTab":            "в отступе табуляция — в YAML только пробелы",
	"deploy.yamlHintQuote":          "не закрыта кавычка или скобка [ ] — проверьте строку и соседние",
	"deploy.yamlHintFieldTop":       "неизвестный ключ «%s» на верхнем уровне; допустимы: %s",
	"deploy.yamlHintField":          "неизвестный ключ «%s» в «%s:»; допустимы: %s (или сбит отступ — ключ попал не в тот блок)",
	"deploy.yamlHintFieldAny":       "неизвестный ключ «%s» (или сбит отступ — ключ попал не в тот блок)",
	"deploy.yamlHintInt":            "ожидается число",
	"deploy.yamlHintList":           "ожидается список: [a, b] или строки «- a» ниже",
	"deploy.yamlHintMap":            "ожидается блок: «ключ: значение» на строках ниже, на 2 пробела глубже",
	"deploy.yamlHintNotString":      "ожидается одно значение, а указан блок или список",
	"deploy.yamlHintBool":           "ожидается true или false",
	"deploy.yamlHintValueBlock":     "у ключа «%[1]s» уже есть значение «%[3]s», а ниже — вложенный блок: оставьте что-то одно. Для сайта блоком имя пишется в domains:, после «site:» на той же строке — ничего",
	"deploy.sitePortIsHost":         "site.port %d — это порт на хосте в «%s»; site.port — порт внутри контейнера: %d",
	"deploy.sitePortAuto":           "  сайт: port auto → %d (из образа %s)",
	"deploy.sitePortAutoMany":       "site.port: auto — образ %s объявляет порты: %s; укажите port явно",
	"deploy.drySitePortAutoMany":    "✗ сайт: port auto, а образ %s объявляет порты: %s — укажите port явно",
	"deploy.sitePortAutoOld":        "site.port: auto — nkt на %s старый, порт образа не узнать; обновите nkt или укажите port",
	"deploy.sitePortAutoUnknown":    "site.port: auto — порт образа не узнать (фикстуры или образ ещё не скачан); укажите port",
	"hub.siteWrongCert":             "https://%s отвечает сертификатом на %s — не для этого имени: конфигурация сайта не действует (прокси отвечает другим сайтом). Проверьте «Настроить» и журнал; на хосте — nginx -T",
	"compose.diagnose":              "Стек не поднялся — состояние контейнеров:",
	"compose.diagContainer":         "  %s: %s %s (код выхода %d)",
	"compose.diagLogs":              "Последние строки журнала сервиса %s:",
	"compose.upPortBusy":            "Порт %s на хосте уже занят — освободите его или поменяйте публикацию (compose.ports)",
	"compose.upArch":                "Образ собран не для архитектуры этого хоста (exec format error) — нужен образ под неё",
	"compose.upExited":              "Контейнер сервиса %s завершился (код %d) — причина в журнале выше",
	"compose.upRestarting":          "Контейнер сервиса %s перезапускается по кругу — причина в журнале выше",
	"compose.upUnhealthy":           "Сервис %s не прошёл healthcheck — причина в журнале выше",
	"deploy.dryPortBusy":            "✗ порт %s на хосте уже занят (%s) — up упадёт; освободите его или поменяйте compose.ports",
	"deploy.dryImageArch":           "✗ образ %s собран для %s, а хост — %s: контейнер не запустится (exec format error)",
	"compose.upCreated":             "Контейнер сервиса %s создан, но не запущен — причина в журнале выше",
	"deploy.envKeysMissing":         "В .env конвейера нет переменных из compose.env_keys: %s — задайте их в «Доступ» → «.env стека» (хосты не тронуты)",
	"deploy.dryEnvKeysMissing":      "✗ в .env конвейера нет %s (compose.env_keys) — задайте в «Доступ» → «.env стека»",
	"deploy.dryEnvKeysOK":           "  секреты из .env конвейера: %s",
}
