package msgs

// Тексты бота Telegram хаба — отдельным файлом.
func init() {
	for k, v := range ruTelegramCatalog {
		ruCatalog[k] = v
	}
}

// #nosec G101 -- тексты сообщений (ключи вроде auth.tokenInvalid), а не учётные данные.
var ruTelegramCatalog = map[string]string{
	"tg.unknownChat":           "Этот чат хабу не знаком. Номер чата: %d — добавьте его в «Оповещения» → «Бот Telegram».",
	"tg.helpRead":              "Команды:\n/status — сводка по хостам\n/hosts — хосты\n/alerts — последние оповещения\n/pipelines — конвейеры\n/id — номер чата и ваш",
	"tg.helpAdmin":             "Команды:\n/status — сводка по хостам\n/hosts — хосты\n/alerts — последние оповещения\n/pipelines — конвейеры\n/deploy <конвейер> — выкладка (с подтверждением)\n/dryrun <конвейер> — сухой прогон\n/ban <IP> и /unban <IP> — на всех хостах с fail2ban (с подтверждением)\n/id — номер чата и ваш",
	"tg.chatID":                "Чат: %d, вы: %d",
	"tg.denied":                "Действия здесь недоступны: нужен чат с ролью «администратор» (и вы в списке разрешённых, если он задан).",
	"tg.noPipeline":            "Нет конвейера «%s» — /pipelines покажет имена и номера.",
	"tg.confirmDeploy":         "Выложить «%s»?",
	"tg.btnDeploy":             "🚀 Выложить",
	"tg.btnCancel":             "Отмена",
	"tg.banUsage":              "Так: /ban 198.51.100.7 (или подсеть).",
	"tg.confirmBan":            "Забанить %s на всех хостах с fail2ban?",
	"tg.confirmUnban":          "Разбанить %s на всех хостах с fail2ban?",
	"tg.btnBan":                "🚫 Забанить",
	"tg.btnUnban":              "Разбанить",
	"tg.unknownCommand":        "Не знаю такой команды — /help.",
	"tg.cancelled":             "Отменено.",
	"tg.expired":               "Подтверждение устарело или не ваше — повторите команду.",
	"tg.deployStarted":         "Выкладка «%s» запущена — задание %d. Итог пришлю.",
	"tg.jobStarted":            "Задание %d запущено. Итог пришлю.",
	"tg.dryStarted":            "Сухой прогон «%s» — задание %d. Итог пришлю.",
	"tg.status":                "Хостов: %d · отвечают: %d · не отвечают: %d\nПроблем: критичных %d, высоких %d, средних %d",
	"tg.noFindings":            "проблем нет",
	"tg.findings":              "проблем: %d крит., %d выс., %d сред.",
	"tg.noHost":                "Нет хоста %d.",
	"tg.hostUp":                "отвечает",
	"tg.hostDown":              "не отвечает",
	"tg.hostDetail":            "%s (%s) — %s, nkt %s\n%s",
	"tg.noAlerts":              "Оповещений нет.",
	"tg.kind.unreachable":      "не отвечает",
	"tg.kind.recovered":        "снова отвечает",
	"tg.kind.problems":         "новые проблемы",
	"tg.kind.resolved":         "проблемы устранены",
	"tg.kind.job-failed":       "задание не выполнено",
	"tg.kind.rebooted":         "перезагрузился",
	"tg.kind.bans":             "новые баны",
	"tg.kind.deploy-succeeded": "выкладка прошла",
	"tg.kind.deploy-failed":    "выкладка не прошла",
	"tg.noPipelines":           "Конвейеров нет.",
	"tg.noJob":                 "Нет задания %d.",
	"tg.job":                   "Задание %d · %s — %s",
	"tg.jobStatus.queued":      "в очереди",
	"tg.jobStatus.running":     "идёт",
	"tg.jobStatus.succeeded":   "✅ готово",
	"tg.jobStatus.failed":      "❌ ошибка",
	"tg.jobStatus.canceled":    "отменено",
	"tg.jobStatus.interrupted": "прервано",
	"tg.btnOverview":           "🔎 Обзор",
	"tg.btnFindings":           "⚠️ Проблемы",
	"tg.btnLog":                "📜 Журнал",
	"tg.btnRetry":              "🔁 Повторить",
	"tg.badToken":              "Токен бота — вида 123456789:AA… (от @BotFather)",
	"tg.tokenRejected":         "Telegram не принял токен: %s",
	"tg.tooMany":               "Чатов — не больше 50, людей — не больше 200",
	"tg.noToken":               "Сначала задайте токен бота",
	"tg.noChat":                "Чата %d нет в списке",
	"tg.test":                  "Пробное сообщение бота nkt (отправил %s).",
	"slack.helpRead":           "Команды: /nkt status — сводка, /nkt hosts — хосты, /nkt alerts — оповещения, /nkt pipelines — конвейеры, /nkt id — номер канала и ваш.",
	"slack.helpAdmin":          "Команды: /nkt status, /nkt hosts, /nkt alerts, /nkt pipelines; /nkt deploy <конвейер> и /nkt ban|unban <IP> — с подтверждением кнопкой; /nkt dryrun <конвейер>; /nkt id.",
	"slack.unknownChannel":     "Этот канал хабу не знаком: %s — добавьте его в «Оповещения» → «Slack».",
	"slack.ids":                "Канал: %s, вы: %s",
	"slack.badToken":           "Токен бота Slack — вида xoxb-…",
	"slack.tokenRejected":      "Slack не принял токен: %s",
	"slack.badSigning":         "Секрет подписи Slack — 32 шестнадцатеричных знака (Basic Information → Signing Secret)",
	"slack.badChannel":         "Не номер канала Slack: %q (вида C0123ABCD)",
	"slack.badUser":            "Не номер пользователя Slack: %q (вида U0123ABCD)",
	"slack.incomplete":         "Нужны и токен бота, и секрет подписи",
	"slack.noChannel":          "Канала %s нет в списке",
}
