package msgs

// ruTUICatalog holds every internal/tui string, kept in its own file (and
// merged into ruCatalog below) so ru.go/en.go — the HTTP API's own catalog
// — don't balloon to a thousand-plus lines mixing two very different
// consumers. Same tui.* key namespace as enTUICatalog, resolved through the
// same T(lang, key, args...) every API string goes through — see
// internal/tui/app.go's App.T for the TUI's own resolve-once-per-process
// wrapper.
func init() {
	for k, v := range ruTUICatalog {
		ruCatalog[k] = v
	}
}

var ruTUICatalog = map[string]string{
	"tui.loadingHostState":  "Загружаю состояние хоста…",
	"tui.globalHints":       "F5 обновить · r пересканировать · ? помощь · q выход",
	"tui.noProblemsFound":   "проблем не найдено",
	"tui.needsAttention":    "требуют внимания: %d",
	"tui.notesCount":        "замечаний: %d",
	"tui.modeLabel":         "режим",
	"tui.scanLabel":         "скан",
	"tui.working":           "работаю…",
	"tui.readOnly":          "только чтение",
	"tui.mutationsDisabled": "Изменения запрещены настройкой NKT_ALLOW_MUTATIONS=false",
	"tui.doneSuffix":        ": готово",
	"tui.cancel":            "Отмена",
	"tui.execute":           "Выполнить",
	"tui.readyHint":         "Готово. F5 обновить, r пересканировать, ? справка.",
	"tui.scanningHost":      "Сканирую хост…",
	"tui.scanFailed":        "скан не удался: %s",
	"tui.rescanDone":        "хост пересканирован за %d мс, находок: %d",

	"tui.help.title":            "Справка",
	"tui.help.navigation":       "Навигация",
	"tui.help.switchScreen":     "  1…9, 0       перейти на экран",
	"tui.help.tabNextPrev":      "  Tab / Shift+Tab   следующий и предыдущий экран",
	"tui.help.tableNav":         "  ↑ ↓ PgUp PgDn     перемещение по таблице",
	"tui.help.enterDetails":     "  Enter        подробности выбранной строки",
	"tui.help.commonActions":    "Общие действия",
	"tui.help.f5Refresh":        "  F5           обновить данные текущего экрана",
	"tui.help.rRescan":          "  r            пересканировать хост целиком",
	"tui.help.qmarkHelp":        "  ?            эта справка",
	"tui.help.qQuit":            "  q            выход",
	"tui.help.screensHeading":   "Экраны",
	"tui.help.configsKeys":      "  Конфигурации  e править, d различия с версией, v история, u откат",
	"tui.help.servicesKeys":     "  Сервисы       s запустить, x остановить, t перезапустить, l перечитать, c проверить конфиг",
	"tui.help.firewallKeys":     "  Firewall      a добавить правило, x удалить правило",
	"tui.help.certsKeys":        "  Сертификаты   Enter показать файл, g выпустить самоподписанный",
	"tui.help.availabilityKeys": "  Доступность   p проверить сейчас, space пауза и возобновление",
	"tui.help.auditNote":        "Все изменения записываются в журнал под именем %s.",
	"tui.help.mutationsNote":    "Если задано NKT_ALLOW_MUTATIONS=false, действия недоступны.",

	"tui.noData":                      "нет данных",
	"tui.noMeasurementsInPeriod":      "Измерений за период нет.",
	"tui.historyCollectedByScheduler": "Историю собирает фоновый планировщик — запустите сервис netknownsthat.",
	"tui.heatmapLess":                 "меньше",
	"tui.heatmapMore":                 "больше   (максимум %s, ·· — измерений не было)",

	"tui.justNow":    "только что",
	"tui.minutesAgo": "%d мин назад",
	"tui.hoursAgo":   "%d ч назад",
	"tui.daysAgo":    "%d дн назад",

	"tui.severity.critical": "критично",
	"tui.severity.high":     "высокая",
	"tui.severity.medium":   "средняя",
	"tui.severity.low":      "низкая",
	"tui.severity.info":     "инфо",

	"tui.configs.title":                 "Конфигурации",
	"tui.configs.colFile":               "Файл",
	"tui.configs.colService":            "Сервис",
	"tui.configs.colSize":               "Размер",
	"tui.configs.colModified":           "Изменён",
	"tui.configs.listTitle":             "Файлы конфигурации",
	"tui.configs.listTitleCount":        "Файлы конфигурации — %d",
	"tui.configs.contentTitle":          "Содержимое",
	"tui.configs.hints":                 "e править · v история версий · u откат к версии",
	"tui.configs.listError":             "список файлов: %s",
	"tui.configs.readError":             "не удалось прочитать: %s",
	"tui.configs.openError":             "не удалось открыть файл: %s",
	"tui.configs.editorTitle":           "%s — Ctrl+S сохранить, Esc отменить",
	"tui.configs.noteLabel":             "Комментарий к правке",
	"tui.configs.applyLabel":            "Перезагрузить сервис после сохранения",
	"tui.configs.unchanged":             "Файл не изменился — ничего не сохранял.",
	"tui.configs.saving":                "Проверяю и сохраняю %s",
	"tui.configs.rolledBackSuffix":      " — файл возвращён в прежнее состояние",
	"tui.configs.saved":                 "%s сохранён, версия #%d",
	"tui.configs.notValidatedSuffix":    " (проверка конфигурации для этого сервиса недоступна)",
	"tui.configs.appliedSuffix":         ", сервис перезагружен",
	"tui.configs.confirmDiscard":        "Правки не сохранены. Закрыть редактор и потерять их?",
	"tui.configs.emptyHistory":          "История пуста: файл ещё не редактировался через это приложение.",
	"tui.configs.colVersion":            "#",
	"tui.configs.colWhen":               "Когда",
	"tui.configs.colWho":                "Кто",
	"tui.configs.colEvent":              "Событие",
	"tui.configs.colNote":               "Комментарий",
	"tui.configs.versionsTitle":         "История версий — Enter показать различия, Esc закрыть",
	"tui.configs.rollbackTitle":         "Откат — Enter восстановить выбранную версию, Esc закрыть",
	"tui.configs.versionMatchesCurrent": "Версия #%d совпадает с текущим файлом.",
	"tui.configs.diffTitle":             "Различия: версия #%d и текущий файл",
	"tui.configs.confirmRollback":       "Восстановить версию #%d от %s?\n\nТекущее содержимое файла будет заменено.",
	"tui.configs.rollingBack":           "Восстанавливаю версию #%d",

	"tui.overview.attentionTitle":       "Что требует внимания",
	"tui.overview.colService":           "Сервис",
	"tui.overview.colState":             "Состояние",
	"tui.overview.colAutostart":         "Автозапуск",
	"tui.overview.colMemory":            "Память",
	"tui.overview.servicesTitle":        "Сервисы",
	"tui.overview.availabilityTitle":    "Доступность",
	"tui.overview.title":                "Обзор",
	"tui.overview.hints":                "Enter подробности сервиса",
	"tui.overview.statusReadFailed":     "не удалось прочитать состояние хоста",
	"tui.overview.tileAttentionLabel":   "Требуют внимания",
	"tui.overview.tileAttentionNote":    "критичных %d, высоких %d",
	"tui.overview.tileListenersLabel":   "Слушателей объявлено",
	"tui.overview.tileListenersNote":    "публичных %d, с TLS %d",
	"tui.overview.tileContainersLabel":  "Контейнеры",
	"tui.overview.tileContainersNote":   "сетей docker: %d",
	"tui.overview.tileUptimeNote":       "целей %d: живы %d, мертвы %d",
	"tui.overview.tileUptimeNoDataNote": "целей %d, проверок ещё не было",
	"tui.overview.tileUptime24hLabel":   "Доступность за 24 ч",
	"tui.overview.noFindings":           "Проблем не найдено.",
	"tui.overview.moreFindings":         "…ещё %d, см. экран «Проблемы»",
	"tui.overview.packetsSuffix":        "%s пакетов",
	"tui.overview.rulesTotal":           "правил всего: %d",
	"tui.overview.targetsDownSummary":   "целей %d, недоступно сейчас %s",
	"tui.overview.noOutages24h":         "за сутки простоев не зафиксировано",
	"tui.overview.recentOutages":        "последние простои:",

	"tui.findings.colSeverity":      "Серьёзность",
	"tui.findings.colRule":          "Правило",
	"tui.findings.colObject":        "Объект",
	"tui.findings.colWhatsWrong":    "Что не так",
	"tui.findings.detailsTitle":     "Подробности",
	"tui.findings.title":            "Проблемы",
	"tui.findings.filterAll":        "все",
	"tui.findings.filterHintPrefix": "f фильтр: ",
	"tui.findings.titleWithCount":   "Проблемы — показано %d из %d",
	"tui.findings.noneMatchFilter":  "Под выбранный фильтр ничего не подходит.",
	"tui.findings.suggestionLabel":  "Что сделать: ",
	"tui.findings.ruleServiceLine":  "правило %s · сервис %s",
	"tui.findings.objectSuffix":     "· объект %s",
	"tui.findings.fileLabel":        "файл ",

	"tui.map.treeTitle":         "Карта сетевых ресурсов",
	"tui.map.nodeTitle":         "Узел",
	"tui.map.title":             "Карта",
	"tui.map.hints":             "Enter свернуть и развернуть ветку",
	"tui.map.sectionPublic":     "Доступно из внешней сети",
	"tui.map.sectionInternal":   "Только изнутри хоста",
	"tui.map.sectionContainers": "Контейнеры",
	"tui.map.selectNodeHint":    "Выберите узел, чтобы увидеть подробности.",
	"tui.map.stateLabel":        "состояние: ",
	"tui.map.findingsSummary":   "проблем: %d (худшая: %s)",
	"tui.map.leadsTo":           "ведёт к: ",

	"tui.services.colType":               "Тип",
	"tui.services.colName":               "Имя",
	"tui.services.colState":              "Состояние",
	"tui.services.colDetails":            "Подробности",
	"tui.services.colPortsMemory":        "Порты и память",
	"tui.services.selectedPanelTitle":    "Выбранный объект",
	"tui.services.title":                 "Сервисы",
	"tui.services.hints":                 "s запуск · x стоп · t перезапуск · l reload · c проверить конфиг",
	"tui.services.actionUnavailable":     "«%s» недоступно для %s",
	"tui.services.validatingConfig":      "Проверяю конфигурацию %s",
	"tui.services.validationUnavailable": "проверка для этого сервиса недоступна",
	"tui.services.configRejected":        "конфигурация отклонена: %s",
	"tui.services.confirmAction":         "Выполнить «%s» для %s «%s»?",
	"tui.services.kindUnit":              "сервиса",
	"tui.services.kindContainer":         "контейнера",
	"tui.services.kindPodman":            "контейнера Podman",
	"tui.services.kindLXD":               "инстанса LXD",
	"tui.services.kindVM":                "виртуальной машины",
	"tui.services.containerActionDone":   "контейнер %s: %s выполнено",
	"tui.services.podmanActionDone":      "podman-контейнер %s: %s выполнено",
	"tui.services.lxdActionDone":         "lxd-инстанс %s: %s выполнено",
	"tui.services.vmActionDone":          "VM %s: %s выполнено",
	"tui.services.actionDone":            "%s: %s выполнено",
	"tui.services.simulatedSuffix":       " (симуляция, режим снапшота)",
	"tui.services.notInstalled":          "не установлен на хосте",
	"tui.services.tableTitle":            " Сервисы и контейнеры — %d ",
	"tui.services.noPortsPublished":      "портов не публикует",
	"tui.services.unitSuffix":            " · юнит %s",
	"tui.services.stateLineUnit":         " состояние: %s %s   автозапуск: %s   перезапусков: %d\n",
	"tui.services.runningSince":          " работает с %s\n",
	"tui.services.configFilesCount":      " файлы конфигурации (%d): ",
	"tui.services.availableActions":      " доступные действия: %s",
	"tui.services.stateBasic":            " состояние: %s   %s\n",
	"tui.services.podLabel":              " под: %s\n",
	"tui.services.portsPrefix":           " порты: ",
	"tui.services.stateArch":             " состояние: %s   архитектура: %s\n",
	"tui.services.ipv4Prefix":            " IPv4: ",
	"tui.services.ipv4NoData":            " IPv4: нет данных",
	"tui.services.stateVCPUMem":          " состояние: %s   vCPU: %d   память: %s\n",
	"tui.services.persistentAutostart":   " постоянный домен: %s   автозапуск: %s\n",
	"tui.services.disksPrefix":           " диски: ",
	"tui.services.networksPrefix":        " сети: ",
	"tui.services.projectServiceFile":    " проект %s, сервис %s, файл %s\n",
	"tui.services.runningOutsideCompose": "запущен вне compose-файлов",
	"tui.services.declaredNotRunning":    "описан в compose, но не запущен",

	"tui.firewall.colNumber":           "№",
	"tui.firewall.colRuleSource":       "Источник правил",
	"tui.firewall.colChain":            "Цепочка",
	"tui.firewall.colAction":           "Действие",
	"tui.firewall.colPort":             "Порт",
	"tui.firewall.colFrom":             "Откуда",
	"tui.firewall.colPackets":          "Пакетов",
	"tui.firewall.colBytes":            "Байт",
	"tui.firewall.statusPanelTitle":    "Состояние firewall",
	"tui.firewall.hints":               "a добавить правило · x удалить правило ufw",
	"tui.firewall.onlyUfwDeletable":    "Удалять можно только правила ufw — правила iptables и docker меняются вне этого интерфейса",
	"tui.firewall.confirmDelete":       "Удалить правило ufw №%d?\n\n%s",
	"tui.firewall.deletingRule":        "Удаляю правило ufw №%d",
	"tui.firewall.ruleDeleted":         "правило удалено: %s",
	"tui.firewall.fieldProtocol":       "Протокол",
	"tui.firewall.fieldSource":         "Источник (IP или CIDR, пусто — отовсюду)",
	"tui.firewall.fieldComment":        "Комментарий",
	"tui.firewall.addButton":           "Добавить",
	"tui.firewall.addingRule":          "Добавляю правило %s %d/%s",
	"tui.firewall.ruleAdded":           "правило добавлено: %s",
	"tui.firewall.newRuleFormTitle":    " Новое правило ufw ",
	"tui.firewall.tableTitle":          " Правила — ufw %d, пакетный фильтр %d ",
	"tui.firewall.defaultZonePrefix":   "зона по умолчанию: ",
	"tui.firewall.ufwRulesUnavailable": "список правил ufw недоступен: %s",
	"tui.firewall.packetsBytes":        "%s пакетов, %s",
	"tui.firewall.openSockets":         "\n открытых сокетов на хосте: %d",
	"tui.firewall.any":                 "любой",

	"tui.monitor.availability.colResource":                 "Ресурс",
	"tui.monitor.availability.colAddress":                  "Адрес",
	"tui.monitor.availability.colNow":                      "Сейчас",
	"tui.monitor.availability.colUptime24h":                "Доступность 24ч",
	"tui.monitor.availability.colLatency":                  "Задержка",
	"tui.monitor.availability.colChecks":                   "Проверок",
	"tui.monitor.availability.downtimeByHourTitle":         "Недоступность по часам недели",
	"tui.monitor.availability.title":                       "Доступность",
	"tui.monitor.availability.hints":                       "p проверить сейчас · space пауза · w период: ",
	"tui.monitor.windowDay":                                "сутки",
	"tui.monitor.windowWeek":                               "7 дней",
	"tui.monitor.windowTwoWeeks":                           "14 дней",
	"tui.monitor.windowMonth":                              "30 дней",
	"tui.monitor.availability.checking":                    "Проверяю %s",
	"tui.monitor.availability.unreachable":                 "%s недоступен: %s",
	"tui.monitor.availability.respondsIn":                  "%s отвечает за %s",
	"tui.monitor.availability.resuming":                    "возобновляю проверки",
	"tui.monitor.availability.pausing":                     "ставлю проверки на паузу",
	"tui.monitor.availability.resumingFor":                 "возобновляю проверки для %s",
	"tui.monitor.availability.pausingFor":                  "ставлю проверки на паузу для %s",
	"tui.monitor.availability.stateUp":                     "доступен",
	"tui.monitor.availability.stateDown":                   "недоступен",
	"tui.monitor.availability.tableTitle":                  "Ресурсы под наблюдением — %d",
	"tui.monitor.availability.downtimeScaleLabel":          "недоступность",
	"tui.monitor.availability.downtimeByHourTitleWindowed": "Недоступность по часам недели — %s",
	"tui.monitor.availability.sourceLabel":                 " источник: ",
	"tui.monitor.availability.checksLabel":                 "   проверок за сутки: ",
	"tui.monitor.availability.failuresLabel":               "   сбоев: ",
	"tui.monitor.availability.lastError":                   "последняя ошибка: %s",
	"tui.monitor.availability.lastCheckLabel":              " последняя проверка: ",
	"tui.monitor.availability.uptimeLabel":                 " доступность  ",
	"tui.monitor.availability.latencyLabel":                " задержка     ",
	"tui.monitor.availability.byHours":                     "по часам",
	"tui.monitor.availability.outagesFor":                  "простои за %s:",
	"tui.monitor.availability.andMore":                     "…ещё %d",

	"tui.monitor.usage.dockerNetTraffic":    "Сетевой трафик контейнеров",
	"tui.monitor.usage.dockerCPU":           "CPU контейнеров",
	"tui.monitor.usage.dockerMemory":        "Память контейнеров",
	"tui.monitor.usage.firewallTraffic":     "Трафик по правилам firewall",
	"tui.monitor.usage.nginxRequests":       "Запросы nginx",
	"tui.monitor.usage.nginx5xxErrors":      "Ошибки 5xx у nginx",
	"tui.monitor.usage.haproxyRequests":     "Запросы haproxy",
	"tui.monitor.usage.trendTitle":          "Динамика",
	"tui.monitor.usage.topTitle":            "Кто нагружает больше всех",
	"tui.monitor.usage.scheduleTitle":       "Расписание использования",
	"tui.monitor.usage.title":               "Нагрузка",
	"tui.monitor.usage.metricLabel":         "m показатель: ",
	"tui.monitor.usage.periodLabel":         "  w период: ",
	"tui.monitor.usage.stepHour":            "час",
	"tui.monitor.usage.stepDay":             "сутки",
	"tui.monitor.usage.noDataLine1":         "Данных за период нет. Метрики собирает фоновый планировщик — ",
	"tui.monitor.usage.noDataLine2":         "запустите сервис netknownsthat или нажмите r для скана.",
	"tui.monitor.usage.totalPeakPointsStep": "всего %s   пик %s   точек %d   шаг %s",
	"tui.monitor.usage.fixturesWarning":     "режим снапшота: значения синтетические, а не измеренные",
	"tui.monitor.usage.noDataInPeriod":      "Нет данных за период.",
	"tui.monitor.usage.topTitleWithMetric":  "Кто нагружает больше всех — %s",
	"tui.monitor.usage.loadScaleLabel":      "нагрузка",

	"tui.monitor.audit.colAction":           "Действие",
	"tui.monitor.audit.colTarget":           "Объект",
	"tui.monitor.audit.colResult":           "Результат",
	"tui.monitor.audit.colDetails":          "Подробности",
	"tui.monitor.audit.tableTitle":          "Журнал действий",
	"tui.monitor.audit.jobsTitle":           "Фоновые задачи",
	"tui.monitor.audit.title":               "Журнал",
	"tui.monitor.audit.hints":               "Enter полный текст записи",
	"tui.monitor.audit.userLabel":           "пользователь:",
	"tui.monitor.audit.targetLabel":         "объект:      ",
	"tui.monitor.audit.resultLabel":         "результат:   ",
	"tui.monitor.audit.entryTitle":          "Запись журнала",
	"tui.monitor.audit.tableTitleWithCount": "Журнал действий — %d записей",
	"tui.monitor.audit.schedulerNote1":      "Планировщик собирает историю только когда запущен сервис netknownsthat.",
	"tui.monitor.audit.schedulerNote2":      "Терминальный интерфейс читает ту же базу и ничего не собирает сам.",
	"tui.monitor.audit.intervalsLabel":      "интервалы:",
	"tui.monitor.audit.probesLabel":         "пробы",
	"tui.monitor.audit.metricsLabel":        "метрики",
	"tui.monitor.audit.inventoryLabel":      "инвентаризация",
	"tui.monitor.audit.autoRenewLabel":      "авто-renew:",
	"tui.monitor.audit.autoRenewTemplate":   "каждые %s продлевает certbot-сертификаты не старше %d дн. до истечения",

	"tui.certs.colSites":                    "Сайты",
	"tui.certs.colExpires":                  "Истекает",
	"tui.certs.colRemaining":                "Осталось",
	"tui.certs.colKey":                      "Ключ",
	"tui.certs.colIssuer":                   "Издатель",
	"tui.certs.colAutoRenew":                "Автообновление",
	"tui.certs.detailTitle":                 "Сертификат",
	"tui.certs.scheduleTitle":               "Расписание истечения",
	"tui.certs.title":                       "Сертификаты",
	"tui.certs.hints":                       "Enter показать файл · g выпустить самоподписанный · r продлить через certbot · c собрать PEM для haproxy",
	"tui.certs.formNames":                   "Имена через запятую",
	"tui.certs.formService":                 "Сервис",
	"tui.certs.formKeyBits":                 "Длина ключа",
	"tui.certs.formDays":                    "Срок действия, дней",
	"tui.certs.createButton":                "Создать",
	"tui.certs.generatingSelfSigned":        "Генерирую самоподписанный сертификат",
	"tui.certs.certCreatedTitle":            "Сертификат создан",
	"tui.certs.certValidUntil":              " %s\n действителен до %s\n\n",
	"tui.certs.configNotAddedHint":          "Файл в конфигурацию ещё не добавлен — вставьте через редактор (экран «Конфигурации»):\n\n%s\n",
	"tui.certs.certCreatedStatus":           "сертификат создан, отпечаток %s…",
	"tui.certs.generateFormTitle":           "Новый самоподписанный сертификат",
	"tui.certs.lineageExpiryUnknown":        "%s — срок неизвестен",
	"tui.certs.lineageExpiredAgo":           "%s — просрочен %d дн. назад",
	"tui.certs.lineageExpiresToday":         "%s — истекает сегодня",
	"tui.certs.lineageDaysLeft":             "%s — %d дн.",
	"tui.certs.letsencryptReadError":        "Не удалось прочитать /etc/letsencrypt/live: %s",
	"tui.certs.noLineagesFound":             "В /etc/letsencrypt/live не найдено ни одной lineage",
	"tui.certs.newFileOption":               "— новый файл —",
	"tui.certs.formTargetPath":              "Куда записать",
	"tui.certs.combineButton":               "Собрать",
	"tui.certs.combiningPEM":                "Собираю PEM для haproxy",
	"tui.certs.overwrittenNoInsertNeeded":   "Файл %s перезаписан, haproxy перечитал конфигурацию — вставлять ничего не нужно.\n",
	"tui.certs.pemCreatedTitle":             "PEM собран",
	"tui.certs.pemCreatedStatus":            "PEM собран, отпечаток %s…",
	"tui.certs.combineFormTitle":            "Собрать PEM для haproxy из certbot",
	"tui.certs.notManagedByCertbot":         "certbot не управляет этим сертификатом — продлить нечем",
	"tui.certs.confirmRenew":                "Выполнить certbot renew --cert-name %s?",
	"tui.certs.confirmRenewDerivedNote":     "\n\nЭто копия сертификата из %s — продлится оригинал, а эта копия будет автоматически пересобрана из нового сертификата и ключа, после чего перечитается сервис.",
	"tui.certs.starting":                    "Начинаю…",
	"tui.certs.renewProgressTitle":          "Продление %s — Esc скрыть (в фоне продолжится)",
	"tui.certs.renewError":                  "Ошибка: %s",
	"tui.certs.renewDone":                   "Готово.",
	"tui.certs.unreadable":                  "не читается",
	"tui.certs.expiredDaysAgo":              "просрочен на %d дн.",
	"tui.certs.expiresToday":                "истекает сегодня",
	"tui.certs.daysLeft":                    "%d дн.",
	"tui.certs.scheduleNoData":              "Нечего показывать.",
	"tui.certs.scheduleHeader":              " запас до истечения, шкала — год\n\n",
	"tui.certs.fileUnreadable":              "файл не читается",
	"tui.certs.scheduleThresholds":          " пороги: %d дн. — предупреждение, %d дн. — срочно",
	"tui.certs.noSslCertificates":           "В разобранных конфигурациях нет ни одного ssl_certificate.",
	"tui.certs.titleCount":                  "Сертификаты — %d",
	"tui.certs.certErrorLabel":              "ошибка: %s",
	"tui.certs.detailValidity":              " срок: %s — %s   %s\n",
	"tui.certs.issuerLabel":                 " издатель: ",
	"tui.certs.subjectLabel":                " субъект:  ",
	"tui.certs.keyLabel":                    " ключ: ",
	"tui.certs.keyBitsFormat":               "%s %d бит",
	"tui.certs.sigLabel":                    "   подпись: ",
	"tui.certs.chainLabel":                  " цепочка: ",
	"tui.certs.chainCountFormat":            "%d сертификат(а)",
	"tui.certs.selfSignedLabel":             "самоподписанный",
	"tui.certs.servesLabel":                 " обслуживает: ",
	"tui.certs.renewalLabel":                "обновление: %s",
	"tui.certs.derivedCopyPrefix":           "копия certbot, ",
	"tui.certs.renewalAutomatic":            "автоматическое",
	"tui.certs.renewalConfiguredNotRunning": "настроено, но не запускается",
	"tui.certs.renewalCertbotRecordLost":    "запись certbot потеряна",
	"tui.certs.renewalManual":               "вручную",
}
