package parse

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/althq/netknownsthat/internal/collect"
	"github.com/althq/netknownsthat/internal/model"
)

// ServiceSpec describes a service the dashboard knows how to manage.
type ServiceSpec struct {
	Name        string   // logical name used across the app: nginx, haproxy, docker...
	Unit        string   // systemd unit
	Binary      string   // binary used for the availability check
	ConfigFiles []string // files the config editor may open
	Actions     []string // control actions the API exposes
}

// DefaultServiceSpecs is the built-in catalogue. Config file lists are filled in
// by the caller from the parsed inventory.
func DefaultServiceSpecs() []ServiceSpec {
	return []ServiceSpec{
		{Name: model.ServiceNginx, Unit: "nginx", Binary: "nginx",
			Actions: []string{"validate", "reload", "restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceHAProxy, Unit: "haproxy", Binary: "haproxy",
			Actions: []string{"validate", "reload", "restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceCaddy, Unit: "caddy", Binary: "caddy",
			Actions: []string{"validate", "reload", "restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceDocker, Unit: "docker", Binary: "docker",
			Actions: []string{"restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServicePodman, Unit: "podman.socket", Binary: "podman",
			Actions: []string{"restart", "start", "stop", "enable", "disable"}},
		// The snap-packaged LXD daemon's systemd unit is generated by snapd
		// under this name on Ubuntu, the most common install path; a
		// distro-packaged LXD ("lxd.service") would need its own spec.
		{Name: model.ServiceLXD, Unit: "snap.lxd.daemon", Binary: "lxc",
			Actions: []string{"restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceLibvirt, Unit: "libvirtd", Binary: "virsh",
			Actions: []string{"restart", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceUFW, Unit: "ufw", Binary: "ufw",
			Actions: []string{"reload", "start", "stop", "enable", "disable"}},
		{Name: model.ServiceFirewalld, Unit: "firewalld", Binary: "firewall-cmd",
			Actions: []string{"reload", "restart", "start", "stop", "enable", "disable"}},
		{Name: "fail2ban", Unit: "fail2ban", Binary: "fail2ban-client",
			Actions: []string{"restart", "start", "stop", "enable", "disable"}},
	}
}

// ServiceInstallMethod is how InstallTarget says a service's underlying
// package should be installed — apt-get for most of this catalogue, but
// not all of it (see InstallTarget's own comment).
type ServiceInstallMethod string

const (
	InstallViaAPT  ServiceInstallMethod = "apt"
	InstallViaSnap ServiceInstallMethod = "snap"
)

// ServiceInstallInfo is InstallTarget's result.
type ServiceInstallInfo struct {
	Method  ServiceInstallMethod
	Package string
	// Binary is spec.Binary — what a caller checks with collect.Which to
	// decide "already installed" before ever attempting this.
	Binary string
}

// serviceInstallOverride lists services whose apt package name doesn't
// match spec.Name (the default InstallTarget falls back to) — either
// because the real package is spelled differently (docker's own
// default-repo package is docker.io, not "docker"; bare "libvirt" isn't
// installable at all, the daemon lives in libvirt-daemon-system) or
// because it isn't an apt package to begin with (current Debian/Ubuntu
// ship LXD only as a snap — Unit: "snap.lxd.daemon" in DefaultServiceSpecs
// already reflects this). Every other spec's Name already IS its own real
// apt package (nginx, haproxy, caddy, podman, ufw, firewalld, fail2ban),
// so nothing else needs an entry here.
var serviceInstallOverride = map[string]struct {
	Method  ServiceInstallMethod
	Package string
}{
	"docker":  {InstallViaAPT, "docker.io"},
	"lxd":     {InstallViaSnap, "lxd"},
	"libvirt": {InstallViaAPT, "libvirt-daemon-system"},
}

// InstallTarget resolves how to install a known ServiceSpec's underlying
// package. ok is false for any name not in DefaultServiceSpecs() at all —
// callers must treat that as "reject the request", the allowlist that
// keeps a URL path parameter from ever reaching a shell command
// unvalidated (the same role ServiceManager.Action's own s.specs[service]
// lookup already plays for start/stop/restart).
func InstallTarget(service string) (ServiceInstallInfo, bool) {
	for _, spec := range DefaultServiceSpecs() {
		if spec.Name != service {
			continue
		}
		info := ServiceInstallInfo{Method: InstallViaAPT, Package: spec.Name, Binary: spec.Binary}
		if o, has := serviceInstallOverride[service]; has {
			info.Method = o.Method
			info.Package = o.Package
		}
		return info, true
	}
	return ServiceInstallInfo{}, false
}

// systemctlProperties is the fixed property set the status reader asks for.
var systemctlProperties = []string{
	"Description", "ActiveState", "SubState", "UnitFileState",
	"ActiveEnterTimestamp", "MainPID", "MemoryCurrent", "NRestarts",
}

// Services reads the state of every managed unit.
func Services(ctx context.Context, c collect.Collector, specs []ServiceSpec) ([]model.ServiceUnit, model.SourceStatus) {
	started := time.Now()
	status := model.SourceStatus{Name: "services"}
	defer func() { status.DurationMS = time.Since(started).Milliseconds() }()

	out := make([]model.ServiceUnit, 0, len(specs))
	for _, spec := range specs {
		unit := model.ServiceUnit{
			Name:        spec.Name,
			Unit:        spec.Unit,
			ActiveState: "unknown",
			ConfigFiles: spec.ConfigFiles,
			Actions:     spec.Actions,
			Installed:   collect.Which(ctx, c, spec.Binary),
		}

		args := append([]string{"show", spec.Unit}, propertyFlags()...)
		res, err := c.Run(ctx, "systemctl", args...)
		if err != nil {
			status.Warnings = append(status.Warnings, fmt.Sprintf("systemctl show %s: %v", spec.Unit, err))
			out = append(out, unit)
			continue
		}
		status.Available = true
		applyUnitProperties(&unit, res.Stdout)
		out = append(out, unit)
	}

	if !status.Available {
		status.Error = "systemctl недоступен: состояние сервисов прочитать не удалось"
		status.ErrorKey = "parse.systemctlUnavailable"
	}
	return out, status
}

func propertyFlags() []string {
	flags := make([]string, 0, len(systemctlProperties)*2)
	for _, p := range systemctlProperties {
		flags = append(flags, "-p", p)
	}
	return flags
}

func applyUnitProperties(unit *model.ServiceUnit, stdout string) {
	for _, line := range strings.Split(strings.ReplaceAll(stdout, "\r\n", "\n"), "\n") {
		key, value, ok := strings.Cut(strings.TrimSpace(line), "=")
		if !ok {
			continue
		}
		switch key {
		case "Description":
			unit.Description = value
		case "ActiveState":
			if value != "" {
				unit.ActiveState = value
			}
		case "SubState":
			unit.SubState = value
		case "UnitFileState":
			unit.Enabled = value
		case "ActiveEnterTimestamp":
			unit.SinceText = value
		case "MainPID":
			unit.MainPID, _ = strconv.Atoi(value)
		case "MemoryCurrent":
			// systemd reports "[not set]" for units without memory accounting.
			if n, err := strconv.ParseInt(value, 10, 64); err == nil {
				unit.MemoryBytes = n
			}
		case "NRestarts":
			unit.Restarts, _ = strconv.Atoi(value)
		}
	}
	if unit.Enabled == "not-found" {
		unit.Installed = false
	}
}
